import { useEffect, useState } from 'react';
import { createId as id, today } from '../../shared/app-utils';
type Category='Skincare'|'Cabelo'|'Corpo'|'Unhas';
type Routine={id:string;title:string;category:Category;time:string;period:string;doneDate?:string};
type Product={id:string;name:string;category:Category;opened:string;expires:string};
type Appointment={id:string;title:string;date:string;notes:string};
const categories:Category[]=['Skincare','Cabelo','Corpo','Unhas'];
const icons:Record<Category,string>={Skincare:'✨',Cabelo:'💆‍♀️',Corpo:'🧴',Unhas:'💅'};
export default function BeautyCare(){
const [tab,setTab]=useState<'today'|'routines'|'products'|'calendar'>('today'),[routines,setRoutines]=useState<Routine[]>(()=>JSON.parse(localStorage.getItem('essence:beauty-routines')||'[]')),[products,setProducts]=useState<Product[]>(()=>JSON.parse(localStorage.getItem('essence:beauty-products')||'[]')),[appointments,setAppointments]=useState<Appointment[]>(()=>JSON.parse(localStorage.getItem('essence:beauty-appointments')||'[]'));
useEffect(()=>localStorage.setItem('essence:beauty-routines',JSON.stringify(routines)),[routines]);useEffect(()=>localStorage.setItem('essence:beauty-products',JSON.stringify(products)),[products]);useEffect(()=>localStorage.setItem('essence:beauty-appointments',JSON.stringify(appointments)),[appointments]);
const completed=routines.filter(x=>x.doneDate===today()).length,progress=routines.length?Math.round(completed/routines.length*100):0,upcoming=[...appointments].filter(x=>x.date>=today()).sort((a,b)=>a.date.localeCompare(b.date));
return <section className="beauty-care"><article className="beauty-hero"><div><b>SEU CUIDADO, SEU MOMENTO</b><h3>Beleza & Cuidados</h3><p>Organize seus rituais de autocuidado com leveza e constância.</p></div><span>🪞</span></article><nav className="tabs beauty-tabs">{([['today','Hoje'],['routines','Rotinas'],['products','Produtos'],['calendar','Calendário']] as const).map(([key,label])=><button type="button" className={tab===key?'active':''} onClick={()=>setTab(key)} key={key}>{label}</button>)}</nav>
{tab==='today'&&<><article className="card beauty-progress"><small>PROGRESSO DE HOJE</small><strong>{progress}%</strong><p>{completed} de {routines.length} cuidados concluídos</p><div className="progress"><span style={{width:`${progress}%`}}/></div></article><article className="card"><h3>✨ Seus cuidados de hoje</h3>{routines.length?[...routines].sort((a,b)=>a.time.localeCompare(b.time)).map(x=><div className="beauty-routine" key={x.id}><label><input type="checkbox" checked={x.doneDate===today()} onChange={()=>setRoutines(all=>all.map(item=>item.id===x.id?{...item,doneDate:item.doneDate===today()?undefined:today()}:item))}/><span><b>{icons[x.category]} {x.title}</b><small>{x.period} · {x.time||'sem horário'} · {x.category}</small></span></label></div>):<div className="empty"><h3>Comece seu ritual</h3><p>Crie sua primeira rotina de autocuidado.</p><button className="primary" onClick={()=>setTab('routines')}>Criar rotina</button></div>}</article><aside className="beauty-reminder">💜 <span><b>Lembrete gentil</b>Autocuidado não é vaidade, é uma forma de se acolher.</span></aside></>}
{tab==='routines'&&<><article className="card"><h3>+ Criar cuidado</h3><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setRoutines(a=>[...a,{id:id(),title:String(f.get('title')),category:String(f.get('category')) as Category,time:String(f.get('time')),period:String(f.get('period'))}]);e.currentTarget.reset()}}><label className="wide">Nome do cuidado<input name="title" placeholder="Ex.: Protetor solar" required/></label><label>Categoria<select name="category">{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Período<select name="period"><option>Manhã</option><option>Noite</option><option>Qualquer horário</option></select></label><label>Horário<input name="time" type="time" defaultValue="08:00"/></label><button className="primary">Adicionar cuidado</button></form></article><article className="card"><h3>Minhas rotinas</h3>{routines.length?routines.map(x=><div className="row" key={x.id}><span><b>{icons[x.category]} {x.title}</b><br/><small>{x.category} · {x.period} · {x.time}</small></span><button onClick={()=>setRoutines(a=>a.filter(y=>y.id!==x.id))}>Excluir</button></div>):<p className="empty">Nenhum cuidado criado ainda.</p>}</article></>}
{tab==='products'&&<><article className="card"><h3>+ Adicionar produto</h3><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setProducts(a=>[{id:id(),name:String(f.get('name')),category:String(f.get('category')) as Category,opened:String(f.get('opened')),expires:String(f.get('expires'))},...a]);e.currentTarget.reset()}}><label className="wide">Produto<input name="name" placeholder="Ex.: Hidratante facial" required/></label><label>Categoria<select name="category">{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Abertura<input name="opened" type="date" defaultValue={today()}/></label><label>Validade<input name="expires" type="date"/></label><button className="primary">Salvar produto</button></form></article><article className="card"><h3>Meus produtos</h3>{products.length?products.map(x=><div className="row" key={x.id}><span><b>{icons[x.category]} {x.name}</b><br/><small>{x.category}{x.opened?` · aberto em ${x.opened}`:''}{x.expires?` · validade ${x.expires}`:''}</small></span><button onClick={()=>setProducts(a=>a.filter(y=>y.id!==x.id))}>Excluir</button></div>):<p className="empty">Adicione produtos para acompanhar abertura e validade.</p>}</article></>}
{tab==='calendar'&&<><article className="card"><h3>+ Agendar cuidado</h3><form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setAppointments(a=>[{id:id(),title:String(f.get('title')),date:String(f.get('date')),notes:String(f.get('notes'))},...a]);e.currentTarget.reset()}}><label className="wide">Cuidado ou procedimento<input name="title" placeholder="Ex.: Manutenção das unhas" required/></label><label>Data<input name="date" type="date" defaultValue={today()} required/></label><label className="wide">Observações<input name="notes" placeholder="Local ou detalhes"/></label><button className="primary">Agendar</button></form></article><article className="card"><h3>Próximos cuidados</h3>{upcoming.length?upcoming.map(x=><div className="row" key={x.id}><span><b>📅 {x.title}</b><br/><small>{x.date}{x.notes?` · ${x.notes}`:''}</small></span><button onClick={()=>setAppointments(a=>a.filter(y=>y.id!==x.id))}>Excluir</button></div>):<p className="empty">Nenhum cuidado agendado.</p>}</article></>}</section>}
