import { useEffect, useMemo, useRef, useState } from 'react';
import { createId as id, today } from '../../shared/app-utils';
import { removeAppReminder, requestReminderPermission, syncDatedReminder } from '../../shared/reminders';
import { readStoredArray } from '../../shared/storage';
type Task={id:string;title:string;date:string;time?:string;category?:string;priority:string;notes?:string;reminder?:string;recurrence?:string;recurrenceEnd?:string;seriesId?:string;done:boolean};
const cats=['Pessoal','Trabalho','Casa','Saúde','Estudos','Outro'];
const dateLabel=(v:string)=>new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(new Date(v+'T12:00:00'));
const reminderLabel=(v:string)=>v==='0'?'no horário':v==='60'?'1 hora antes':v+' min antes';
const recurrenceLabel=(v:string)=>v==='daily'?'Diariamente':v==='weekly'?'Semanalmente':'Mensalmente';
const recurringDates=(start:string,repeat:string,end:string)=>{if(!repeat)return [start];const base=new Date(start+'T12:00:00'),limit=end?new Date(end+'T12:00:00'):null,max=repeat==='daily'?90:repeat==='weekly'?52:12,dates=[start];for(let i=1;i<=max;i++){let next:Date;if(repeat==='monthly'){const year=base.getFullYear()+Math.floor((base.getMonth()+i)/12),month=(base.getMonth()+i)%12,day=Math.min(base.getDate(),new Date(year,month+1,0).getDate());next=new Date(year,month,day,12)}else{next=new Date(base);next.setDate(base.getDate()+i*(repeat==='weekly'?7:1))}if(limit&&next>limit)break;dates.push(isoDate(next))}return dates};
const isoDate=(d:Date)=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
const weekFor=(offset:number)=>{const base=new Date(today()+'T12:00:00');const weekday=(base.getDay()+6)%7;base.setDate(base.getDate()-weekday+offset*7);return Array.from({length:7},(_,i)=>{const date=new Date(base);date.setDate(base.getDate()+i);return isoDate(date)})};
export default function Agenda(){
const [tasks,setTasks]=useState<Task[]>(()=>readStoredArray<Task>('essence:tasks'));const [confirmAction,setConfirmAction]=useState<{kind:'delete'|'series';task:Task}|null>(null);
const [now,setNow]=useState(()=>Date.now());const [dismissedReminder,setDismissedReminder]=useState('');
const [weekOffset,setWeekOffset]=useState(0);const [selectedDate,setSelectedDate]=useState(today());const weekDays=weekFor(weekOffset);
const [formError,setFormError]=useState('');const [tab,setTab]=useState<'today'|'upcoming'|'all'>('today');const [category,setCategory]=useState('Todas');const [status,setStatus]=useState<'pending'|'done'|'all'>('pending');const [message,setMessage]=useState('');const [formOpen,setFormOpen]=useState(false);const [editing,setEditing]=useState<Task|null>(null);const formRef=useRef<HTMLFormElement>(null);const [pomodoroSeconds,setPomodoroSeconds]=useState(25*60);const [pomodoroRunning,setPomodoroRunning]=useState(false);const [pomodoroSessions,setPomodoroSessions]=useState(0);const [pomodoroFocus,setPomodoroFocus]=useState('');
useEffect(()=>localStorage.setItem('essence:tasks',JSON.stringify(tasks)),[tasks]);
useEffect(()=>{const timer=window.setInterval(()=>setNow(Date.now()),30000);return()=>window.clearInterval(timer)},[]);useEffect(()=>{if(!pomodoroRunning)return;const timer=window.setInterval(()=>setPomodoroSeconds(seconds=>{if(seconds<=1){window.clearInterval(timer);setPomodoroRunning(false);setPomodoroSessions(value=>value+1);return 0}return seconds-1}),1000);return()=>window.clearInterval(timer)},[pomodoroRunning]);
const ordered=useMemo(()=>[...tasks].sort((a,b)=>(a.date+(a.time||'23:59')).localeCompare(b.date+(b.time||'23:59'))),[tasks]);const activeReminder=ordered.find(t=>{if(t.done||!t.time||t.reminder===undefined||t.reminder===''||t.id===dismissedReminder)return false;const due=new Date(t.date+'T'+t.time+':00').getTime();return now>=due-Number(t.reminder)*60000&&now<=due+300000});const next=ordered.find(t=>!t.done&&t.date>=today());const todayTasks=tasks.filter(t=>t.date===today());const completed=todayTasks.filter(t=>t.done).length;
const visible=ordered.filter(t=>(tab==='today'?t.date===selectedDate:tab==='upcoming'?t.date>=today():true)&&(category==='Todas'||(t.category||'Pessoal')===category)&&(status==='all'||(status==='pending'?!t.done:t.done)));
const notify=(text:string)=>{setMessage(text);window.setTimeout(()=>setMessage(''),3200)};const toggleTask=(task:Task)=>{const done=!task.done;setTasks(all=>all.map(item=>item.id===task.id?{...item,done}:item));if(done)removeAppReminder(task.id);else if(task.reminder!==undefined&&task.reminder!==''&&task.time)syncDatedReminder(task.id,'Compromisso: '+task.title,task.date,task.time,Number(task.reminder))};const openCreate=()=>{setFormError('');setEditing(null);setFormOpen(true);window.setTimeout(()=>formRef.current?.querySelector<HTMLInputElement>('input[name="title"]')?.focus(),0)};const openEdit=(t:Task)=>{setFormError('');setEditing(t);setFormOpen(true);window.setTimeout(()=>formRef.current?.scrollIntoView({behavior:'smooth',block:'center'}),0)};const closeForm=()=>{setFormError('');setEditing(null);setFormOpen(false)};
const tomorrow=(t:Task)=>{const d=new Date();d.setDate(d.getDate()+1);const date=isoDate(d),conflict=tasks.find(x=>x.id!==t.id&&!x.done&&x.date===date&&x.time&&x.time===t.time);if(conflict&&!window.confirm('Já existe “'+conflict.title+'” nesse horário amanhã. Deseja reagendar mesmo assim?'))return;setTasks(a=>a.map(x=>x.id===t.id?{...x,date,done:false}:x));if(t.reminder!==undefined&&t.reminder!==''&&t.time)syncDatedReminder(t.id,'Compromisso: '+t.title,date,t.time,Number(t.reminder));notify('“'+t.title+'” foi movido para amanhã.')};
const confirmRemoval=()=>{if(!confirmAction)return;const {kind,task}=confirmAction;if(kind==='delete'){removeAppReminder(task.id);setTasks(a=>a.filter(x=>x.id!==task.id));notify('“'+task.title+'” foi excluído.')}else{tasks.filter(x=>x.seriesId===task.seriesId&&x.date>=task.date).forEach(x=>removeAppReminder(x.id));setTasks(a=>a.filter(x=>x.seriesId!==task.seriesId||x.date<task.date));notify('Recorrência encerrada.')}setConfirmAction(null)};
const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setFormError('');const f=new FormData(e.currentTarget),title=String(f.get('title')).trim();if(!title){setFormError('Informe o nome do compromisso.');return}const repeat=String(f.get('recurrence')),recurrenceEnd=String(f.get('recurrenceEnd'));const value={title,date:String(f.get('date')),time:String(f.get('time')),category:String(f.get('category')),priority:String(f.get('priority')),notes:String(f.get('notes')),reminder:String(f.get('reminder')),recurrence:repeat,recurrenceEnd};if(value.reminder&&!value.time){setFormError('Defina um horário para usar o lembrete.');return}if(recurrenceEnd&&recurrenceEnd<value.date){setFormError('A data final da recorrência deve ser igual ou posterior à data inicial.');return}const dates=editing?[value.date]:recurringDates(value.date,repeat,recurrenceEnd),conflict=tasks.find(t=>t.id!==editing?.id&&!t.done&&value.time&&t.time===value.time&&dates.includes(t.date));if(conflict&&!window.confirm('Já existe “'+conflict.title+'” em '+dateLabel(conflict.date)+' às '+conflict.time+'. Deseja salvar mesmo assim?'))return;if(editing){setTasks(a=>a.map(x=>x.id===editing.id?{...x,...value}:x));if(value.reminder!==''&&value.time){syncDatedReminder(editing.id,'Compromisso: '+title,value.date,value.time,Number(value.reminder));void requestReminderPermission()}else removeAppReminder(editing.id);notify('“'+title+'” foi atualizado.')}else{const seriesId=repeat?id():undefined,created=dates.map(date=>({id:id(),...value,date,seriesId,done:false}));setTasks(a=>[...created,...a]);created.forEach(task=>{if(task.reminder!==''&&task.time)syncDatedReminder(task.id,'Compromisso: '+task.title,task.date,task.time,Number(task.reminder))});if(value.reminder!==''&&value.time)void requestReminderPermission();notify(repeat?dates.length+' ocorrências de “'+title+'” foram adicionadas.':'“'+title+'” foi adicionado à sua agenda.')}closeForm()};
return <section className="agenda">
<article className="workout-hero agenda-hero"><div><b>SEU TEMPO, DO SEU JEITO</b><h3>Agenda inteligente</h3><p>Visualize prioridades e organize o dia sem sobrecarregar sua rotina.</p></div><button type="button" className="primary" onClick={openCreate}>+ Novo compromisso</button></article>
<div className="agenda-overview"><article className="card agenda-today"><span className="agenda-icon">✓</span><div><small>PROGRESSO DE HOJE</small><h3>{todayTasks.length?completed+' de '+todayTasks.length+' concluídos':'Dia livre por aqui'}</h3><div className="agenda-progress"><span style={{width:(todayTasks.length?Math.round(completed/todayTasks.length*100):0)+'%'}}/></div><p>{todayTasks.length?(todayTasks.length-completed)+' compromisso(s) pendente(s)':'Você ainda não adicionou compromissos para hoje.'}</p></div></article>
<article className="card agenda-next"><span className="agenda-icon">↗</span><div><small>PRÓXIMO COMPROMISSO</small>{next?<><h3>{next.title}</h3><p><b>{next.date===today()?'Hoje':dateLabel(next.date)}</b>{next.time?' às '+next.time:''} · {next.category||'Pessoal'}</p>{next.notes&&<em>{next.notes}</em>}</>:<><h3>Nada programado</h3><p>Adicione algo quando fizer sentido para você.</p></>}</div></article></div>
<article className="card pomodoro-card"><div className="pomodoro-head"><div><small>FOCO COM LEVEZA</small><h3>Pomodoro</h3></div><span>{pomodoroSessions} sessão(ões) hoje</span></div><div className="pomodoro-clock"><b>{String(Math.floor(pomodoroSeconds/60)).padStart(2,'0')}:{String(pomodoroSeconds%60).padStart(2,'0')}</b><small>{pomodoroRunning?'foco em andamento':'pronta para começar'}</small></div><div className="pomodoro-presets">{[25,15,5].map(minutes=><button type="button" className={pomodoroSeconds===minutes*60&&!pomodoroRunning?'selected':''} key={minutes} onClick={()=>{setPomodoroRunning(false);setPomodoroSeconds(minutes*60)}}>{minutes} min</button>)}</div><label className="pomodoro-focus">No que você quer focar?<input value={pomodoroFocus} onChange={event=>setPomodoroFocus(event.target.value)} placeholder="Ex.: responder mensagens"/></label><div className="pomodoro-actions"><button type="button" onClick={()=>{setPomodoroRunning(false);setPomodoroSeconds(25*60)}} aria-label="Reiniciar Pomodoro">↻</button><button type="button" className="primary" onClick={()=>setPomodoroRunning(value=>!value)}>{pomodoroRunning?'Pausar':'Começar foco'} ▶</button></div></article>
{activeReminder&&<div className="agenda-reminder" role="alert"><span>🔔</span><div><small>LEMBRETE DA AGENDA</small><b>{activeReminder.title}</b><p>{activeReminder.time} · {reminderLabel(activeReminder.reminder||"0")}</p></div><button type="button" onClick={()=>setDismissedReminder(activeReminder.id)}>Entendi</button></div>}
{formOpen&&<article className="card agenda-form-card"><div className="card-head"><div><small>{editing?'EDITAR COMPROMISSO':'NOVO COMPROMISSO'}</small><h3>{editing?'Atualize os detalhes':'O que você quer organizar?'}</h3></div><button type="button" onClick={closeForm}>Fechar</button></div><form ref={formRef} className="form" onSubmit={submit}><label className="wide">Título<input name="title" defaultValue={editing?.title||''} placeholder="Ex.: Consulta ou reunião" required/></label><label>Data<input name="date" type="date" defaultValue={editing?.date||today()} required/></label><label>Horário<input name="time" type="time" defaultValue={editing?.time||''}/></label><label>Lembrete<select name="reminder" defaultValue={editing?.reminder||''}><option value="">Sem lembrete</option><option value="0">No horário</option><option value="15">15 minutos antes</option><option value="30">30 minutos antes</option><option value="60">1 hora antes</option></select></label><label>Repetir<select name="recurrence" defaultValue={editing?.recurrence||''}><option value="">Não repetir</option><option value="daily">Diariamente</option><option value="weekly">Semanalmente</option><option value="monthly">Mensalmente</option></select></label><label>Repetir até (opcional)<input name="recurrenceEnd" type="date" min={editing?.date||today()} defaultValue={editing?.recurrenceEnd||''}/></label><label>Categoria<select name="category" defaultValue={editing?.category||'Pessoal'}>{cats.map(x=><option key={x}>{x}</option>)}</select></label><label>Prioridade<select name="priority" defaultValue={editing?.priority||'Normal'}><option>Normal</option><option>Alta</option><option>Baixa</option></select></label><label className="wide">Observação opcional<textarea name="notes" defaultValue={editing?.notes||''} placeholder="Local, preparo ou lembrete importante"/></label>{formError&&<p className="agenda-form-error wide" role="alert">{formError}</p>}<button className="primary wide">{editing?'Salvar alterações':'Adicionar à agenda'}</button></form></article>}
{message&&<div className="agenda-toast" role="status">✓ {message}</div>}
<article className="card agenda-list"><div className="card-head agenda-commitments-head"><div><small>SEU PLANEJAMENTO</small><h3>Compromissos</h3></div><span className="agenda-filters"><select aria-label="Filtrar por categoria" value={category} onChange={e=>setCategory(e.target.value)}><option>Todas</option>{cats.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filtrar por status" value={status} onChange={e=>setStatus(e.target.value as 'pending'|'done'|'all')}><option value="pending">Pendentes</option><option value="done">Concluídos</option><option value="all">Todos</option></select></span></div>
<div className="agenda-week"><div className="agenda-week-head"><button type="button" aria-label="Semana anterior" onClick={()=>setWeekOffset(v=>v-1)}>‹</button><b>{dateLabel(weekDays[0])}, {dateLabel(weekDays[6])}</b><button type="button" aria-label="Próxima semana" onClick={()=>setWeekOffset(v=>v+1)}>›</button></div><div className="agenda-week-days">{weekDays.map(date=>{const count=tasks.filter(t=>t.date===date&&!t.done).length;return <button type="button" key={date} className={selectedDate===date?"selected":""} onClick={()=>{setSelectedDate(date);setTab("today")}}><small>{new Intl.DateTimeFormat("pt-BR",{weekday:"short"}).format(new Date(date+"T12:00:00")).replace(".","")}</small><b>{Number(date.slice(-2))}</b>{count>0&&<span>{count}</span>}</button>})}</div></div>
<div className="symptoms agenda-periods">{([['today','Dia'],['upcoming','Próximos dias'],['all','Tudo']] as const).map(([v,l])=><button type="button" key={v} className={tab===v?'selected':''} onClick={()=>setTab(v)}>{l}</button>)}</div>
<div className="agenda-items">{visible.length?visible.map(t=><div className={'agenda-item'+(t.done?' is-done':'')} key={t.id}><label className="agenda-check"><input type="checkbox" aria-label={(t.done?"Reabrir ":"Concluir ")+t.title} checked={t.done} onChange={()=>toggleTask(t)}/><span><b>{t.title}</b><small>{t.date===today()?'Hoje':dateLabel(t.date)}{t.time?' · '+t.time:''} · {t.category||'Pessoal'}{t.reminder!==undefined&&t.reminder!==''&&t.time?' · 🔔 '+reminderLabel(t.reminder):''}{t.recurrence?' · ↻ '+recurrenceLabel(t.recurrence):''}</small>{t.notes&&<em>{t.notes}</em>}</span></label><span className={'agenda-priority priority-'+t.priority.toLowerCase()}>{t.priority}</span><span className="agenda-actions"><button type="button" onClick={()=>openEdit(t)}>Editar</button>{!t.done&&<button type="button" onClick={()=>tomorrow(t)}>Amanhã</button>}{t.seriesId&&<button type="button" className="series-stop" onClick={()=>setConfirmAction({kind:"series",task:t})}>Encerrar série</button>}<button type="button" className="agenda-delete" onClick={()=>setConfirmAction({kind:"delete",task:t})}>Excluir</button></span></div>):<div className="empty agenda-empty"><span>📅</span><h3>{tab==='today'?(selectedDate===today()?'Seu tempo está livre hoje':'Nenhum compromisso neste dia'):'Nada por aqui ainda'}</h3><p>{tab==='today'?(selectedDate===today()?'Você pode descansar ou planejar algo importante.':'Escolha outro dia ou adicione um compromisso.'):'Ajuste os filtros ou adicione um novo compromisso.'}</p><button type="button" className="primary" onClick={openCreate}>+ Adicionar compromisso</button></div>}</div></article>{confirmAction&&<div className="agenda-modal-backdrop" role="presentation" onClick={()=>setConfirmAction(null)} onKeyDown={e=>{if(e.key==="Escape")setConfirmAction(null)}}><div className="agenda-confirm-modal" role="dialog" aria-modal="true" aria-labelledby="agenda-confirm-title" onClick={e=>e.stopPropagation()}><span className="agenda-confirm-icon">{confirmAction.kind==="delete"?"🗑️":"↻"}</span><small>CONFIRMAR AÇÃO</small><h3 id="agenda-confirm-title">{confirmAction.kind==="delete"?"Excluir compromisso?":"Encerrar recorrência?"}</h3><p><b>“{confirmAction.task.title}”</b></p><p>{confirmAction.kind==="delete"?(confirmAction.task.seriesId?"Somente esta ocorrência será removida. As demais continuam na agenda.":"Este compromisso será removido da sua agenda."):"Esta ocorrência e todas as futuras serão removidas. As anteriores permanecem."}</p><div className="agenda-confirm-actions"><button type="button" autoFocus onClick={()=>setConfirmAction(null)}>Cancelar</button><button type="button" className="agenda-confirm-danger" onClick={confirmRemoval}>{confirmAction.kind==="delete"?"Sim, excluir":"Encerrar série"}</button></div></div></div>}</section>}