import { useState } from 'react';
import type { Dispatch, SetStateAction } from 'react';
import { today } from '../../shared/app-utils';
import type { LocalAccount, LocalSession } from '../../shared/app.types';

export default function Onboarding({session,onComplete}:{session:LocalSession;onComplete:(session:LocalSession)=>void}){
  const [step,setStep]=useState(1);const [name,setName]=useState(session.name);const [goals,setGoals]=useState<string[]>([]);const [rhythm,setRhythm]=useState('Equilibrado');const [reminders,setReminders]=useState<string[]>([]);
  const toggle=(value:string,setList:Dispatch<SetStateAction<string[]>>)=>setList(current=>current.includes(value)?current.filter(item=>item!==value):[...current,value]);
  const finish=()=>{const cleanName=name.trim()||session.name;const data={completed:true,name:cleanName,goals,rhythm,reminders,completedAt:today()};localStorage.setItem('essence:onboarding',JSON.stringify(data));const saved=localStorage.getItem('essence:account');if(saved){const account:LocalAccount=JSON.parse(saved);localStorage.setItem('essence:account',JSON.stringify({...account,name:cleanName}))}onComplete({...session,name:cleanName})};
  return <main className="onboarding-page"><section className="onboarding-panel"><div className="onboarding-brand">✦ Essence Life</div><div className="onboarding-step">Passo {step} de 3</div>{step===1&&<><h1>Vamos conhecer você</h1><p>Com algumas escolhas, preparamos uma experiência mais parecida com o seu momento.</p><label>Como prefere ser chamada?<input value={name} onChange={event=>setName(event.target.value)} placeholder="Ex.: Aline" autoFocus/></label><h3>O que você quer cuidar agora?</h3><div className="choice-grid">{['Rotina','Sono','Nutrição','Treinos','Finanças','Bem-estar'].map(goal=><button type="button" key={goal} className={goals.includes(goal)?'selected':''} onClick={()=>toggle(goal,setGoals)}>{goal}</button>)}</div><button type="button" className="primary onboarding-next" onClick={()=>setStep(2)}>Continuar</button></>}{step===2&&<><h1>Seu ritmo, suas escolhas</h1><p>Você poderá mudar tudo depois no Perfil.</p><label>Como está seu ritmo hoje?<select value={rhythm} onChange={event=>setRhythm(event.target.value)}><option>Leve</option><option>Equilibrado</option><option>Focado</option></select></label><h3>Quando os lembretes fazem mais sentido?</h3><div className="choice-grid">{['Manh?','Tarde','Noite'].map(time=><button type="button" key={time} className={reminders.includes(time)?'selected':''} onClick={()=>toggle(time,setReminders)}>{time}</button>)}</div><div className="onboarding-actions"><button type="button" onClick={()=>setStep(1)}>Voltar</button><button type="button" className="primary" onClick={()=>setStep(3)}>Continuar</button></div></>}{step===3&&<><h1>Seu espaço está pronto</h1><p>Seu espaço está preparado. O acesso aos módulos segue o plano confirmado na sua compra.</p><div className="onboarding-summary"><b>Foco: {goals.length?goals.join(', '):'Sua rotina'}</b><span>Ritmo: {rhythm}</span><span>Lembretes: {reminders.length?reminders.join(', '):'Você decide depois'}</span></div><button type="button" className="primary onboarding-next" onClick={finish}>Entrar no Essence Life</button><button type="button" className="onboarding-back" onClick={()=>setStep(2)}>Voltar</button></>}</section></main>
}
