import { useState } from 'react';
import type { Dispatch, SetStateAction } from 'react';
import { applyAppSettings, readAppSettings, themePresets } from '../../shared/app-settings';
import type { ThemePreset } from '../../shared/app-settings';
import { createId, today } from '../../shared/app-utils';
import type { LocalAccount, LocalSession } from '../../shared/app.types';
import { requestReminderPermission, syncAppReminder, syncDatedReminder } from '../../shared/reminders';

type FirstAction='task'|'habit'|'commitment';

export default function Onboarding({session,onComplete}:{session:LocalSession;onComplete:(session:LocalSession)=>void}){
const [step,setStep]=useState(1);const [name,setName]=useState(session.name);const [goals,setGoals]=useState<string[]>([]);const [preset,setPreset]=useState<ThemePreset>(readAppSettings().preset);const [actionType,setActionType]=useState<FirstAction>('task');const [actionTitle,setActionTitle]=useState('');const [actionTime,setActionTime]=useState('09:00');const [reminder,setReminder]=useState(true);
const toggle=(value:string,setList:Dispatch<SetStateAction<string[]>>)=>setList(current=>current.includes(value)?current.filter(item=>item!==value):[...current,value]);
const chooseTheme=(value:ThemePreset)=>{setPreset(value);const current=readAppSettings(),next={...current,preset:value,accent:themePresets[value].accent};localStorage.setItem('essence:app-settings',JSON.stringify(next));applyAppSettings(next)};
const saveFirstAction=()=>{const title=actionTitle.trim();if(!title)return;const actionId=createId();if(actionType==='habit'){const entries=JSON.parse(localStorage.getItem('essence:routine-items')||'[]');entries.unshift({id:actionId,name:title,time:actionTime,category:'Pessoal',days:['SEG','TER','QUA','QUI','SEX','SÁB','DOM'],reminderEnabled:reminder,reminderTime:actionTime,done:false});localStorage.setItem('essence:routine-items',JSON.stringify(entries));syncAppReminder(actionId,'Hábito: '+title,actionTime,reminder)}else{const entries=JSON.parse(localStorage.getItem('essence:tasks')||'[]');entries.unshift({id:actionId,title,date:today(),time:actionTime,category:actionType==='commitment'?'Compromisso':'Pessoal',priority:'Normal',reminderEnabled:reminder,reminderTime:actionTime,done:false});localStorage.setItem('essence:tasks',JSON.stringify(entries));if(reminder)syncDatedReminder(actionId,(actionType==='commitment'?'Compromisso: ':'Tarefa: ')+title,today(),actionTime)}if(reminder)void requestReminderPermission()};
const finish=(skipped=false)=>{const cleanName=name.trim()||session.name;if(!skipped)saveFirstAction();localStorage.setItem('essence:onboarding',JSON.stringify({completed:true,name:cleanName,goals,preset,firstAction:actionTitle.trim()?actionType:null,skipped,completedAt:today()}));localStorage.removeItem('essence:onboarding-review');const saved=localStorage.getItem('essence:account');if(saved){const account:LocalAccount=JSON.parse(saved);localStorage.setItem('essence:account',JSON.stringify({...account,name:cleanName}))}onComplete({...session,name:cleanName})};
const next=()=>setStep(value=>Math.min(4,value+1));const back=()=>setStep(value=>Math.max(1,value-1));
return <main className="onboarding-page"><section className="onboarding-panel"><header className="onboarding-header"><div className="onboarding-brand">✦ Essence Life</div><button type="button" onClick={()=>finish(true)}>Pular por agora</button></header><div className="onboarding-progress"><span style={{width:`${step*25}%`}}/></div><div className="onboarding-step">Passo {step} de 4</div>
{step===1&&<><h1>Vamos deixar o app com a sua cara</h1><p>Escolha o que deseja cuidar primeiro. Assim destacamos os módulos mais úteis para você.</p><label>Como prefere ser chamada?<input value={name} onChange={event=>setName(event.target.value)} placeholder="Ex.: Aline" autoFocus/></label><h3>Quais são seus objetivos agora?</h3><div className="choice-grid onboarding-goals">{[['🗓️','Organizar a rotina'],['🌙','Dormir melhor'],['🥗','Cuidar da alimentação'],['🏋️','Movimentar o corpo'],['💰','Organizar finanças'],['🌸','Cuidar de mim']].map(([icon,goal])=><button type="button" key={goal} className={goals.includes(goal)?'selected':''} onClick={()=>toggle(goal,setGoals)}><span>{icon}</span>{goal}</button>)}</div><button type="button" className="primary onboarding-next" onClick={next}>Continuar</button></>}
{step===2&&<><h1>Escolha uma atmosfera</h1><p>O tema será aplicado em todos os módulos e poderá ser alterado em Configurações.</p><div className="onboarding-theme-grid">{Object.entries(themePresets).map(([key,item])=><button type="button" key={key} className={preset===key?'selected':''} onClick={()=>chooseTheme(key as ThemePreset)}><span className="theme-preset-preview" style={{'--preview-bg':item.background,'--preview-surface':item.surface,'--preview-accent':item.accent,'--preview-border':item.border} as React.CSSProperties}><i/><i/><i/></span><b>{item.icon} {item.label}</b><small>{item.description}</small></button>)}</div><div className="onboarding-actions"><button type="button" onClick={back}>Voltar</button><button type="button" className="primary" onClick={next}>Continuar</button></div></>}
{step===3&&<><h1>Crie seu primeiro passo</h1><p>Comece com algo simples. A ação aparecerá no seu dia e poderá avisar você no horário escolhido.</p><div className="choice-grid onboarding-action-types">{([['task','✓','Tarefa'],['habit','✦','Hábito'],['commitment','🗓️','Compromisso']] as const).map(([value,icon,label])=><button type="button" className={actionType===value?'selected':''} onClick={()=>setActionType(value)} key={value}><span>{icon}</span>{label}</button>)}</div><label>O que você quer lembrar?<input value={actionTitle} onChange={event=>setActionTitle(event.target.value)} placeholder={actionType==='habit'?'Ex.: Beber água ao acordar':actionType==='commitment'?'Ex.: Consulta médica':'Ex.: Organizar documentos'}/></label><label>Horário<input type="time" value={actionTime} onChange={event=>setActionTime(event.target.value)}/></label><label className="onboarding-reminder"><input type="checkbox" checked={reminder} onChange={event=>setReminder(event.target.checked)}/><span><b>Ativar lembrete</b><small>O aplicativo solicitará permissão para enviar a notificação.</small></span></label><div className="onboarding-actions"><button type="button" onClick={back}>Voltar</button><button type="button" className="primary" onClick={next}>Continuar</button></div></>}
{step===4&&<><h1>Tudo pronto para começar</h1><p>Explore o app no seu ritmo e reveja estes primeiros passos em Configurações.</p><div className="onboarding-plan-grid"><article><small>ESSENCIAL</small><h3>Organização para o dia a dia</h3><p>Recursos essenciais para rotina, agenda e bem-estar.</p></article><article className="featured"><small>PRO</small><h3>Experiência completa</h3><p>Todos os módulos, recursos avançados e novidades.</p></article></div><div className="onboarding-summary"><b>Seu início personalizado</b><span>Objetivos: {goals.length?goals.join(', '):'Você decide depois'}</span><span>Tema: {themePresets[preset].label}</span><span>Primeiro passo: {actionTitle.trim()||'Criar depois no app'}</span></div><button type="button" className="primary onboarding-next" onClick={()=>finish(false)}>Entrar no Essence Life</button><button type="button" className="onboarding-back" onClick={back}>Voltar</button></>}
</section></main>}
