import { useEffect } from 'react';
import { today } from '../shared/app-utils';
import { readAppReminders } from '../shared/reminders';

const decodeKey=(value:string)=>{const padded=value.replaceAll('-','+').replaceAll('_','/')+'='.repeat((4-value.length%4)%4);const raw=atob(padded);return Uint8Array.from(raw,char=>char.charCodeAt(0))};
const onlineToken=()=>{try{return JSON.parse(localStorage.getItem('essence:online-session')||'null')?.accessToken||''}catch{return''}};
const nextOccurrence=(date:string|undefined,time:string)=>{const now=new Date();const target=new Date(`${date||today()}T${time}:00`);if(!date&&target<=now)target.setDate(target.getDate()+1);return target};

export function useReminderNotifications(){useEffect(()=>{
  const show=async(title:string)=>{const options={body:title,icon:'/icon-192.png',badge:'/icon-192.png',tag:'essence-reminder'};try{if('serviceWorker' in navigator){const registration=await navigator.serviceWorker.ready;await registration.showNotification('Essence Life',options)}else new Notification('Essence Life',options)}catch{try{new Notification('Essence Life',{body:title})}catch{}}};
  const syncPush=async()=>{if(!('serviceWorker' in navigator)||!('PushManager' in window)||Notification.permission!=='granted'||!navigator.onLine)return;const token=onlineToken();if(!token)return;try{const configResponse=await fetch('/api/push/config');if(!configResponse.ok)return;const{publicKey}=await configResponse.json();const registration=await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription();if(!subscription)subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:decodeKey(publicKey)});const reminders=readAppReminders().filter(item=>item.enabled&&item.time).map(item=>({id:item.id,title:item.title,remindAt:nextOccurrence(item.date,item.time).toISOString(),repeatDaily:!item.date})).filter(item=>Date.parse(item.remindAt)>Date.now()-60000);await fetch('/api/push/register',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({subscription:subscription.toJSON(),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,reminders})});localStorage.setItem('essence:push-last-sync',new Date().toISOString())}catch{}}
  const tick=()=>{if(!('Notification' in window)||Notification.permission!=='granted')return;const now=new Date();const clock=now.toTimeString().slice(0,5);const stamp=today()+'-'+clock;readAppReminders().filter(reminder=>reminder.enabled&&reminder.time===clock&&(!reminder.date||reminder.date===today())).forEach(reminder=>{const key='essence:reminder-fired:'+reminder.id;if(localStorage.getItem(key)===stamp)return;void show(reminder.title);localStorage.setItem(key,stamp)})};
  const requestSync=()=>void syncPush();tick();void syncPush();const tickTimer=window.setInterval(tick,30000);const syncTimer=window.setInterval(()=>void syncPush(),60000);window.addEventListener('essence:push-sync-request',requestSync);window.addEventListener('online',requestSync);return()=>{window.clearInterval(tickTimer);window.clearInterval(syncTimer);window.removeEventListener('essence:push-sync-request',requestSync);window.removeEventListener('online',requestSync)}
},[])}