import type { OnlineSession } from '../modules/auth/auth-api';

const SUPABASE_URL=import.meta.env.VITE_SUPABASE_URL||'https://snnqwkjwnnbibikqeurr.supabase.co';
const SUPABASE_KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_dPL3lYONn3QfLE_41tg3xg_Et0LwU6I';
const CLOUD_KEYS=['essence:profile','essence:app-settings'] as const;
type CloudRow={data:Record<string,string>};
const headers=(session:OnlineSession)=>({apikey:SUPABASE_KEY,authorization:`Bearer ${session.accessToken}`,'content-type':'application/json'});
export function readCloudSnapshot(email?:string){return Object.fromEntries(CLOUD_KEYS.flatMap(key=>{const value=localStorage.getItem(key);if(value===null)return[];if(key==='essence:profile'&&email){try{if(JSON.parse(value)?.email?.toLowerCase()!==email.toLowerCase())return[]}catch{return[]}}return[[key,value]]}))}
function applyCloudSnapshot(data:Record<string,string>){let changed=false;for(const key of CLOUD_KEYS){const value=data?.[key];if(typeof value==='string'&&localStorage.getItem(key)!==value){localStorage.setItem(key,value);changed=true}}return changed}
async function saveSnapshot(session:OnlineSession,data:Record<string,string>){const response=await fetch(`${SUPABASE_URL}/rest/v1/user_cloud_state?on_conflict=user_id`,{method:'POST',headers:{...headers(session),prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:session.user.id,data,device_updated_at:new Date().toISOString(),updated_at:new Date().toISOString()})});if(!response.ok)throw new Error('Não foi possível sincronizar os dados agora.')}
export async function restoreCloudState(session:OnlineSession){const response=await fetch(`${SUPABASE_URL}/rest/v1/user_cloud_state?select=data&user_id=eq.${encodeURIComponent(session.user.id)}&limit=1`,{headers:headers(session)});if(!response.ok)return false;const rows=await response.json() as CloudRow[];const local=readCloudSnapshot(session.user.email);if(!rows.length){await saveSnapshot(session,local);return false}const cloud=rows[0]?.data||{};if(!Object.keys(cloud).length&&Object.keys(local).length){await saveSnapshot(session,local);return false}return applyCloudSnapshot(cloud)}
export function startCloudSync(session:OnlineSession){let last=JSON.stringify(readCloudSnapshot(session.user.email)),saving=false;const sync=async()=>{const snapshot=readCloudSnapshot(session.user.email),serialized=JSON.stringify(snapshot);if(serialized===last||saving||!navigator.onLine)return;saving=true;try{await saveSnapshot(session,snapshot);last=serialized;window.dispatchEvent(new CustomEvent('essence:cloud-synced'))}catch{}finally{saving=false}};const timer=window.setInterval(()=>void sync(),1800);const online=()=>void sync();window.addEventListener('online',online);return()=>{window.clearInterval(timer);window.removeEventListener('online',online)}}