import type { OnlineSession } from '../modules/auth/auth-api';

const SUPABASE_URL=import.meta.env.VITE_SUPABASE_URL||'https://snnqwkjwnnbibikqeurr.supabase.co';
const SUPABASE_KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_dPL3lYONn3QfLE_41tg3xg_Et0LwU6I';
const CLOUD_KEYS=['essence:profile','essence:app-settings','essence:tasks','essence:routine-items','essence:routine-history','essence:reminders','essence:water-entries','essence:water-goal','essence:checkin-date','essence:sleeps','essence:sleep-goal','essence:sleep-routine','essence:sleep-environment','essence:sleep-sound-favorites','essence:sleep-sound-recent','essence:meals','essence:nutrition-plan','essence:nutrition-profile','essence:nutrition-progress','essence:purchases','essence:workouts','essence:workout-sessions','essence:beauty-routines','essence:beauty-products','essence:beauty-appointments','essence:beauty-history','essence:house-tasks','essence:projects','essence:diary','essence:diary-draft','essence:diary-letters','essence:diary-pin','essence:cycle','essence:cycle-settings','essence:cycle-care','essence:cycle-kit','essence:finance','essence:finance-budgets','essence:finance-goals'] as const;
type CloudRow={data:Record<string,string>;updated_at:string};
type CloudSyncStatus='synced'|'syncing'|'offline'|'error'|'conflict';
type Conflict={remote:Record<string,string>;updatedAt:string};
let lastCloudUpdate='';
const headers=(session:OnlineSession)=>({apikey:SUPABASE_KEY,authorization:`Bearer ${session.accessToken}`,'content-type':'application/json'});
export function readCloudSnapshot(email?:string){return Object.fromEntries(CLOUD_KEYS.flatMap(key=>{const value=localStorage.getItem(key);if(value===null)return[];if(key==='essence:profile'&&email){try{if(JSON.parse(value)?.email?.toLowerCase()!==email.toLowerCase())return[]}catch{return[]}}return[[key,value]]}))}
function applyCloudSnapshot(data:Record<string,string>){let changed=false;for(const key of CLOUD_KEYS){const value=data?.[key];if(typeof value==='string'&&localStorage.getItem(key)!==value){localStorage.setItem(key,value);changed=true}}return changed}
async function readRemote(session:OnlineSession){const response=await fetch(`${SUPABASE_URL}/rest/v1/user_cloud_state?select=data,updated_at&user_id=eq.${encodeURIComponent(session.user.id)}&limit=1`,{headers:headers(session)});if(!response.ok)throw new Error('Não foi possível consultar a sincronização.');const rows=await response.json() as CloudRow[];return rows[0]||null}
async function saveSnapshot(session:OnlineSession,data:Record<string,string>){const response=await fetch(`${SUPABASE_URL}/rest/v1/user_cloud_state?on_conflict=user_id`,{method:'POST',headers:{...headers(session),prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({user_id:session.user.id,data,device_updated_at:new Date().toISOString()})});if(!response.ok)throw new Error('Não foi possível sincronizar os dados agora.');const [saved]=await response.json() as CloudRow[];lastCloudUpdate=saved?.updated_at||lastCloudUpdate}
function emitStatus(status:CloudSyncStatus,message=''){const updatedAt=status==='synced'?new Date().toISOString():localStorage.getItem('essence:cloud-last-synced')||'';if(status==='synced')localStorage.setItem('essence:cloud-last-synced',updatedAt);window.dispatchEvent(new CustomEvent('essence:cloud-sync-status',{detail:{status,message,updatedAt}}))}
export async function restoreCloudState(session:OnlineSession){const row=await readRemote(session);const local=readCloudSnapshot(session.user.email);if(!row){await saveSnapshot(session,local);return false}lastCloudUpdate=row.updated_at||'';const cloud=row.data||{};const changed=applyCloudSnapshot(cloud);const merged=readCloudSnapshot(session.user.email);if(CLOUD_KEYS.some(key=>localStorage.getItem(key)!==null&&typeof cloud[key]!=='string'))await saveSnapshot(session,merged);return changed}
export function startCloudSync(session:OnlineSession){let last=JSON.stringify(readCloudSnapshot(session.user.email)),busy=false,conflict:Conflict|null=null;
const sync=async()=>{if(busy||conflict)return;if(!navigator.onLine){emitStatus('offline','Seus dados continuam salvos neste dispositivo.');return}busy=true;emitStatus('syncing');try{const snapshot=readCloudSnapshot(session.user.email),serialized=JSON.stringify(snapshot);const remote=await readRemote(session);const localChanged=serialized!==last;const remoteChanged=!!remote?.updated_at&&remote.updated_at>lastCloudUpdate;if(localChanged&&remoteChanged){conflict={remote:remote?.data||{},updatedAt:remote?.updated_at||''};emitStatus('conflict','Há alterações neste dispositivo e também na nuvem. Escolha qual versão deseja manter.');return}if(localChanged){await saveSnapshot(session,snapshot);last=serialized}else if(remoteChanged&&remote){lastCloudUpdate=remote.updated_at;if(applyCloudSnapshot(remote.data||{})){last=JSON.stringify(readCloudSnapshot(session.user.email));emitStatus('synced');window.location.reload();return}}emitStatus('synced')}catch(reason){emitStatus(navigator.onLine?'error':'offline',reason instanceof Error?reason.message:'Não foi possível sincronizar agora.')}finally{busy=false}};
const resolveConflict=(event:Event)=>{if(!conflict)return;const strategy=(event as CustomEvent<{strategy:'device'|'cloud'}>).detail?.strategy;if(strategy==='device'){const snapshot=readCloudSnapshot(session.user.email);conflict=null;void saveSnapshot(session,snapshot).then(()=>{last=JSON.stringify(snapshot);emitStatus('synced')}).catch(reason=>emitStatus('error',reason instanceof Error?reason.message:'Não foi possível sincronizar.'))}else if(strategy==='cloud'){const selected=conflict;conflict=null;lastCloudUpdate=selected.updatedAt;applyCloudSnapshot(selected.remote);localStorage.setItem('essence:cloud-last-synced',new Date().toISOString());window.location.reload()}};
const timer=window.setInterval(()=>void sync(),4000);const online=()=>void sync();const offline=()=>emitStatus('offline','Seus dados continuam salvos neste dispositivo.');const retry=()=>void sync();window.addEventListener('online',online);window.addEventListener('offline',offline);window.addEventListener('essence:cloud-sync-request',retry);window.addEventListener('essence:cloud-conflict-resolve',resolveConflict);void sync();return()=>{window.clearInterval(timer);window.removeEventListener('online',online);window.removeEventListener('offline',offline);window.removeEventListener('essence:cloud-sync-request',retry);window.removeEventListener('essence:cloud-conflict-resolve',resolveConflict)}}