import type { Dispatch, SetStateAction } from 'react';
import { createId as id, today } from '../../shared/app-utils';
type ProgressEntry={id:string;date:string;weight:string;energy:number;hunger:number;satiety:number;notes:string};
type WaterEntry={date:string;ml:number}; type MealEntry={date:string};
export default function NutritionProgress({entries,setEntries,waterEntries,meals}:{entries:ProgressEntry[];setEntries:Dispatch<SetStateAction<ProgressEntry[]>>;waterEntries:WaterEntry[];meals:MealEntry[]}){
 const ordered=[...entries].sort((a,b)=>b.date.localeCompare(a.date));const recent=ordered.slice(0,7);const latest=ordered[0];
 const average=(key:'energy'|'hunger'|'satiety')=>recent.length?(recent.reduce((sum,item)=>sum+item[key],0)/recent.length).toFixed(1):'—';
 const hydrationDays=new Set(waterEntries.filter(entry=>entry.ml>0).map(entry=>entry.date)).size;const mealDays=new Set(meals.map(meal=>meal.date)).size;
 return <><article className="card nutrition-progress-overview"><div className="nutrition-section-head"><div><small>SEU PROGRESSO</small><h3>Tendências com leveza</h3></div><span>{entries.length} registro(s)</span></div><p>Observe como você se sente ao longo do tempo, sem transformar números em cobrança.</p><div className="nutrition-progress-metrics"><article><span>⚡</span><small>ENERGIA MÉDIA</small><b>{average('energy')}/5</b></article><article><span>🍽️</span><small>CONFORTO MÉDIO</small><b>{average('satiety')}/5</b></article><article><span>💧</span><small>HIDRATAÇÃO</small><b>{hydrationDays} dia(s)</b></article><article><span>🥗</span><small>ALIMENTAÇÃO</small><b>{mealDays} dia(s)</b></article></div></article>
 <article className="card nutrition-progress-editor"><div className="card-head"><div><small>NOVO ACOMPANHAMENTO</small><h3>Como você está hoje?</h3><p>Peso e observação são opcionais.</p></div></div><form className="form" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);setEntries(items=>[{id:id(),date:String(form.get('date')),weight:String(form.get('weight')),energy:Number(form.get('energy')),hunger:Number(form.get('hunger')),satiety:Number(form.get('satiety')),notes:String(form.get('notes'))},...items]);event.currentTarget.reset()}}><label>Data<input name="date" type="date" defaultValue={today()} required/></label><label>Peso opcional (kg)<input name="weight" type="number" min="1" step="0.1" placeholder="Ex.: 62,5"/></label><label>Energia<input name="energy" type="range" min="1" max="5" defaultValue="3"/><small>1 baixa · 5 alta</small></label><label>Fome<input name="hunger" type="range" min="1" max="5" defaultValue="3"/><small>1 pouca · 5 muita</small></label><label>Conforto após comer<input name="satiety" type="range" min="1" max="5" defaultValue="3"/><small>1 baixo · 5 alto</small></label><label className="wide">Observação opcional<textarea name="notes" placeholder="Ex.: tive mais disposição e comi com calma"/></label><button className="primary wide">Salvar acompanhamento</button></form></article>
 <article className="card nutrition-progress-history"><div className="card-head"><div><small>HISTÓRICO</small><h3>Seus registros recentes</h3></div>{latest?.weight&&<span>{latest.weight} kg</span>}</div>{ordered.length?<div className="nutrition-progress-list">{ordered.slice(0,10).map(entry=><article key={entry.id}><div><small>{new Date(entry.date+'T12:00:00').toLocaleDateString('pt-BR')}</small><b>{entry.weight?entry.weight+' kg':'Sem peso informado'}</b><p>Energia {entry.energy}/5 · Fome {entry.hunger}/5 · Conforto {entry.satiety}/5</p>{entry.notes&&<em>{entry.notes}</em>}</div><button type="button" onClick={()=>setEntries(items=>items.filter(item=>item.id!==entry.id))}>Excluir</button></article>)}</div>:<div className="empty"><h3>Seu progresso começa aqui</h3><p>Registre como você se sente para acompanhar tendências no seu próprio ritmo.</p></div>}</article></>
}