import type { ReactNode } from 'react';
import type { LocalSession } from '../shared/app.types';
import { pageMeta, planNames, requiredPlanForPage } from '../shared/access-control';
import type { AppPage } from '../shared/access-control';

type AuthenticatedLayoutProps={session:LocalSession;page:AppPage;mobileNavOpen:boolean;onToggleMobileNav:()=>void;openPage:(page:AppPage)=>void;isLocked:(page:AppPage)=>boolean;showPlanLocks:boolean;onLogout:()=>void;children:ReactNode};

function AuthenticatedLayout({session,page,mobileNavOpen,onToggleMobileNav,openPage,isLocked,showPlanLocks,onLogout,children}:AuthenticatedLayoutProps){
const nav=(key:AppPage,label:string,icon:string)=><button type="button" className={(page===key?'active':'')+(!['home','settings','profile'].includes(key)&&isLocked(key)?' locked':'')} onClick={event=>{event.preventDefault();event.stopPropagation();if(key==='settings')window.dispatchEvent(new CustomEvent('essence:open-settings'));else openPage(key)}}><span>{icon}</span><span>{label}</span>{showPlanLocks&&!['home','settings','profile'].includes(key)&&isLocked(key)&&<small>🔒 {planNames[requiredPlanForPage(key)]}</small>}</button>;
const currentMeta=pageMeta[page];
return <div className="app"><header className="mobile-topbar"><button type="button" className="mobile-menu-button" onClick={onToggleMobileNav} aria-expanded={mobileNavOpen} aria-label={mobileNavOpen?"Fechar menu":"Abrir menu"}><span aria-hidden="true">{mobileNavOpen?"×":"☰"}</span><small>{mobileNavOpen?"Fechar":"Menu"}</small></button><button type="button" className="mobile-brand" onClick={()=>openPage('home')} aria-label="Ir para o início"><img src="/essence-life-logo.png" alt="" className="brand-logo"/><span><strong>Essence Life</strong><small>Seu bem-estar em equilíbrio</small></span></button><button type="button" className="mobile-profile-button" onClick={()=>openPage('profile')} aria-label="Abrir perfil">{session.avatar?<img src={session.avatar} alt={'Foto de '+session.name}/>:<span>{session.name.slice(0,1).toUpperCase()}</span>}<i aria-hidden="true"/></button></header><aside className={mobileNavOpen?"mobile-open":""}><div className="nav-identity"><img src="/essence-life-logo.png" alt="" className="nav-logo"/><div><h1 className="nav-brand">Essence Life</h1><small>Olá, {session.name.split(' ')[0]}</small></div></div><div className="nav-groups"><section className="nav-group"><p className="nav-section-title">Meu dia</p>{nav('home','Início','🏠')}{nav('agenda','Agenda','📅')}{nav('pomodoro','Pomodoro','⏱️')}{nav('routine','Rotina','🗓️')}{nav('diary','Diário','📘')}{nav('insights','Insights','✨')}</section><section className="nav-group"><p className="nav-section-title">Bem-estar</p>{nav('sleep','Sono','🌙')}{nav('nutrition','Nutrição','🥗')}{nav('cycle','Ciclo','🌸')}{nav('workouts','Treinos','🏋️')}{nav('beauty','Beleza & Cuidados','🪞')}</section><section className="nav-group"><p className="nav-section-title">Organização</p>{nav('finance','Finanças','💰')}<button className={(page==='house'?'active':'')+(isLocked('house')?' locked':'')} onClick={()=>openPage('house')}><span>🏡</span><span>Casa & Compras</span>{showPlanLocks&&isLocked('house')&&<small>🔒 {planNames[requiredPlanForPage('house')]}</small>}</button></section><section className="nav-group nav-account-group"><p className="nav-section-title">Conta</p>{nav('settings','Configurações','⚙️')}{nav('profile','Perfil','👤')}<button className="logout" type="button" onClick={onLogout}><span>↪</span><span>Sair</span></button></section></div></aside><main>{page==='home'||page==='profile'?<header className="content-header"><div><h2>{currentMeta.title}</h2><p>{currentMeta.copy}</p></div></header>:null}{children}</main></div>}

export default AuthenticatedLayout;
