import { useState } from 'react';
import Landing from './Landing';

type MapOption={id:string;icon:string;title:string;detail:string};
const mapQuestions:[string,string,MapOption[]][]=[
['Onde sua energia mais se perde?','Escolha o ponto que mais pede atenção hoje.',[{id:'mind',icon:'◌',title:'Mente cheia',detail:'Muitas ideias, lembretes e decisões ao mesmo tempo'},{id:'time',icon:'◷',title:'Tempo escapando',detail:'O dia termina antes do que era importante'},{id:'care',icon:'♡',title:'Cuidado ficando por último',detail:'Sono, alimentação e pausas sempre podem esperar'},{id:'money',icon:'◇',title:'Vida prática acumulando',detail:'Casa, compras e finanças ocupam espaço demais'}]],
['Que tipo de organização combina com você?','Não existe jeito certo — existe o que você consegue sustentar.',[{id:'visual',icon:'▦',title:'Quero enxergar tudo',detail:'Painéis, progresso e uma visão clara da semana'},{id:'guided',icon:'✦',title:'Quero ser guiada',detail:'Sugestões para não decidir cada passo sozinha'},{id:'simple',icon:'—',title:'Quero o essencial',detail:'Poucas prioridades e uma rotina sem excesso'},{id:'flexible',icon:'↝',title:'Quero liberdade',detail:'Planejar sem transformar o dia em uma regra'}]],
['O que faria você sentir que avançou?','Pense na mudança que teria mais impacto nas próximas semanas.',[{id:'calm',icon:'☼',title:'Terminar o dia mais leve',detail:'Com menos pendências rodando na cabeça'},{id:'steady',icon:'↻',title:'Manter constância',detail:'Continuar mesmo quando a semana sair do plano'},{id:'focus',icon:'◎',title:'Saber o próximo passo',detail:'Começar sem gastar energia escolhendo'},{id:'balance',icon:'≈',title:'Equilibrar as áreas da vida',detail:'Sem precisar abandonar uma para cuidar da outra'}]]
];
function DiscoveryQuiz(){
const [step,setStep]=useState(0),[answers,setAnswers]=useState<string[]>([]),[phase,setPhase]=useState<'quiz'|'loading'|'result'|'offer'>('quiz');if(phase==='offer')return <Landing/>;const question=mapQuestions[step];
const select=(option:MapOption)=>{if(phase!=='quiz')return;const next=[...answers,option.id];setAnswers(next);if(step===mapQuestions.length-1){setPhase('loading');window.setTimeout(()=>setPhase('result'),1500)}else window.setTimeout(()=>setStep(value=>value+1),220)};
const focus=answers[0]==='mind'?'clareza mental':answers[0]==='time'?'prioridades possíveis':answers[0]==='care'?'autocuidado real':'vida prática organizada';const style=answers[1]==='guided'?'com orientação inteligente':answers[1]==='visual'?'com uma visão clara do progresso':answers[1]==='simple'?'com poucos passos por vez':'com flexibilidade para mudar';
return <main className="model-quiz"><span className="model-deco model-deco-a">✦</span><span className="model-deco model-deco-b">♡</span><span className="model-deco model-deco-c">☼</span><span className="model-deco model-deco-d">◇</span><div className="model-shell"><a className="model-brand" href="/"><img src="/essence-life-logo.png" alt=""/><span>Essence Life</span></a>{phase==='quiz'&&<><div className="model-status"><span>{Math.round((step+1)/mapQuestions.length*100)}%</span></div><div className="model-progress"><i style={{width:`${(step+1)/mapQuestions.length*100}%`}}/></div><div className="model-dots">{mapQuestions.map((_,index)=><i key={index} className={index<=step?'active':''}/>)}</div>{step===0&&<div className="model-intro"><span>SEU MAPA DA ROTINA</span><h1>Descubra por onde começar a organizar sua vida.</h1><p>Três escolhas rápidas. Um ponto de partida feito para o seu momento.</p></div>}<section className="model-card" key={step}><span className="model-step">ETAPA {step+1} DE {mapQuestions.length}</span><h2>{question[0]}</h2><p>{question[1]}</p><div className="model-options">{question[2].map(option=><button type="button" key={option.id} onClick={()=>select(option)}><i>{option.icon}</i><span><b>{option.title}</b><small>{option.detail}</small></span><em>○</em></button>)}</div></section><small className="model-note">Escolha o que parece verdadeiro para você agora.</small></>}{phase==='loading'&&<section className="model-loading"><div className="model-loader">✦</div><h1>Organizando suas escolhas…</h1><div><p>✓ Identificando sua prioridade</p><p>✓ Entendendo seu jeito de organizar</p><p>• Preparando seu ponto de partida</p></div></section>}{phase==='result'&&<section className="model-card model-result"><span className="model-result-tag">✦ SEU MAPA ESSENCE</span><h1>Seu começo pede mais {focus}.</h1><h2>Sem mudar tudo de uma vez.</h2><p>Para o seu momento, a melhor direção é organizar a vida <strong>{style}</strong>. Assim, constância deixa de depender de uma rotina perfeita.</p><div className="model-result-list"><div><i>01</i><span><b>Centralize</b><small>Tire tarefas, ideias e compromissos da cabeça.</small></span></div><div><i>02</i><span><b>Priorize</b><small>Enxergue o que realmente precisa acontecer agora.</small></span></div><div><i>03</i><span><b>Continue</b><small>Acompanhe seu ritmo sem recomeçar do zero.</small></span></div></div><button type="button" onClick={()=>{setPhase('offer');window.scrollTo(0,0)}}>VER MINHA EXPERIÊNCIA <span>→</span></button><small>Na próxima etapa você conhece os recursos e os planos.</small></section>}</div></main>}

export default DiscoveryQuiz;
