import { useState } from 'react';

type Mode = 'today' | 'water' | 'smart';

export default function Landing() {
  const [mode, setMode] = useState<Mode>('today');
  const [waterLevel, setWaterLevel] = useState(900);
  const openApp = () => window.location.assign('/app');
  const checkouts = { mensal: 'https://pay.kiwify.com.br/yIJKlLK', trimestral: 'https://pay.kiwify.com.br/UKuHm32', anual: 'https://pay.kiwify.com.br/a1CTCMt' } as const;
  const buy = (plan: keyof typeof checkouts) => window.location.assign(checkouts[plan]);
  const waterLiters = (waterLevel / 1000).toLocaleString('pt-BR', { minimumFractionDigits: 1, maximumFractionDigits: 1 });
  return <main className="sales-flow">
    <header className="sales-header"><a href="/" className="sales-brand"><img src="/essence-life-logo.png" alt=""/>Essence Life</a><button onClick={openApp}>Já tenho acesso</button></header>
    <section className="sales-hero"><div className="sales-copy"><span className="sales-pill">✦ SUA ROTINA, DO SEU JEITO</span><h1>Sua rotina, em um só lugar.</h1><p>Lembre, planeje e cuide de você com mais leveza.</p><button className="sales-cta" onClick={()=>document.getElementById('experimente')?.scrollIntoView({behavior:'smooth'})}>CONHECER O ESSENCE LIFE <b>→</b></button><div className="sales-mini"><span>📱 No celular e computador</span><span>✦ Apoio inteligente</span></div></div><div className="sales-phone"><div className="phone-top"><small>10:42</small><b>Essence Life</b><small>☼</small></div></div></section>
    <section className="sales-trust"><article><i>⚡</i><b>Acesso imediato</b><span>Comece assim que sua compra for confirmada.</span></article><article><i>♡</i><b>7 dias de garantia</b><span>Conheça a experiência com tranquilidade.</span></article><article><i>🔒</i><b>Compra segura</b><span>Pagamento processado pela Kiwify.</span></article></section>
    <section id="experimente" className="try-section"><span className="sales-pill">✦ EXPERIMENTE A SENSAÇÃO</span><h2>Toque em um item e sinta como funciona.</h2><div className="try-tabs">{([['today','Seu dia'],['water','Água'],['smart','IA']] as const).map(([key,label])=><button key={key} className={mode===key?'active':''} onClick={()=>setMode(key)}>{label}</button>)}</div><div className="try-cards" data-mode={mode}/><article className="water-demo" aria-label="Demonstração de registro de água"><div><span>💧 HIDRATAÇÃO DE HOJE</span><b>{waterLiters} L</b><small>de 2,5 L</small></div><div className="water-bar" aria-hidden="true"><i style={{width:`${Math.min(100,waterLevel/25)}%`}}/></div><button type="button" onClick={()=>{setMode('water');setWaterLevel(level=>Math.min(2500,level+250))}}>+ 250 ml</button><small className="water-hint">Toque para registrar um copo e preencher a barra.</small></article></section>
    <section className="feature-split"><div><span>ROTINA POSSÍVEL</span><h2>Pare de montar sua rotina do zero toda semana.</h2><p>Tudo o que importa para o seu dia, sem excesso.</p><ul><li>Visão do dia, da semana e do mês</li><li>Lembretes no horário que você escolhe</li><li>Hábitos flexíveis para não desistir na primeira semana difícil</li></ul></div><aside><small>✦ IA QUANDO VOCÊ PRECISAR</small><b>Uma base de rotina em minutos, feita para adaptar.</b><p>Peça uma sugestão para rotina, treino, alimentação ou autocuidado e deixe com a sua cara.</p></aside></section>
    <section className="feature-split reverse"><aside className="habit-card"><small>CONSTÂNCIA</small><b>Hábitos que finalmente ficam de pé.</b><p>Sem meta irreal. Você escolhe o ritmo e acompanha cada pequeno avanço.</p></aside><div><span>VIDA REAL</span><h2>Cuide de tudo sem esquecer de você.</h2><p>Use só o que fizer sentido para você.</p><ul><li>Registre sua água e refeições com leveza</li><li>Organize treinos e uma rotina de sono possível</li><li>Crie alertas para remédios, consultas e cuidados</li></ul></div></section>
    <section id="planos" className="plan-decision"><span>PREMIUM</span><h2>Escolha o ritmo que combina com você.</h2><p>Todos os planos liberam a experiência completa do Essence Life.</p><div className="decision-grid decision-grid-premium"><article><small>PREMIUM MENSAL</small><h3>Comece no seu ritmo</h3><strong><b>R$ 39,90</b></strong><em>por mês · renovação mensal</em><ul><li>Todos os módulos do Essence Life</li><li>IA, lembretes e planejamento inteligente</li><li>Acesso completo enquanto a assinatura estiver ativa</li></ul><button onClick={()=>buy('mensal')}>QUERO O MENSAL →</button></article><article><small>✦ MAIS EQUILÍBRIO</small><h3>Mais tempo para a sua rotina</h3><strong><b>R$ 99,90</b></strong><em>a cada 3 meses</em><p className="decision-saving">Economize R$ 19,80</p><ul><li>Todos os módulos do Essence Life</li><li>IA, lembretes e planejamento inteligente</li><li>Acesso completo enquanto a assinatura estiver ativa</li></ul><button onClick={()=>buy('trimestral')}>QUERO O TRIMESTRAL →</button></article><article className="pro"><small>✦ MELHOR VALOR</small><h3>Um ano de leveza</h3><strong><b>R$ 319,90</b></strong><em>por ano</em><p className="decision-saving">Economize R$ 158,90</p><ul><li>Todos os módulos do Essence Life</li><li>IA, lembretes e planejamento inteligente</li><li>Acesso completo enquanto a assinatura estiver ativa</li></ul><button onClick={()=>buy('anual')}>QUERO O ANUAL →</button></article></div><footer>🔒 Compra 100% segura &nbsp; • &nbsp; ⚡ Acesso imediato &nbsp; • &nbsp; ♡ 7 dias de garantia</footer></section>
  </main>
}