import { useState } from 'react';

type Preview='reminder'|'water'|'ai'|'day';
const modules=[
  {plan:'Essencial',headline:'O apoio para o que não pode ficar só na sua cabeça.',items:[['🔔','Lembretes e agenda','Crie avisos para remédios, consultas, tarefas e tudo que tem hora para acontecer.'],['💧','Rotina e bem-estar','Acompanhe hábitos, água, sono, ciclo e pequenos cuidados do dia.'],['◌','Início e diário','Enxergue prioridades e registre o que você sente sem se cobrar perfeição.']]},
  {plan:'Pro',headline:'Mais recursos para cuidar da vida por inteiro.',items:[['✦','Planejamento com IA','Tenha uma primeira sugestão de rotina, treino, cardápio ou cuidados e deixe tudo com a sua cara.'],['☼','Corpo e autocuidado','Nutrição, treinos, beleza e cuidados para apoiar o seu bem-estar.'],['⌂','Vida prática organizada','Finanças, casa e compras para reduzir a sobrecarga do cotidiano.']]}
];

export default function Landing(){
 const [preview,setPreview]=useState<Preview>('reminder');const [openFaq,setOpenFaq]=useState<number|null>(null);
 const openApp=()=>window.location.assign('/app');const checkout=(plan:string)=>window.location.assign(plan==='Essencial'?'https://pay.kiwify.com.br/l744PMU':'https://pay.kiwify.com.br/qBamiP3');
 const views:Record<Preview,{tag:string;title:string;copy:string;metric:string;rows:[string,string][]}>={
   reminder:{tag:'LEMBRETE GENTIL',title:'Hora do remédio',copy:'Hoje · 08:00',metric:'🔔',rows:[['Beber água','A cada 2 horas'],['Consulta de rotina','Quinta · 14:30']]},
   water:{tag:'CUIDADO POSSÍVEL',title:'Sua água hoje',copy:'1,4 L de 2 L',metric:'70%',rows:[['Pausa para você','Respirar e alongar'],['Rotina noturna','21:30']]},
   ai:{tag:'APOIO INTELIGENTE',title:'Rotina da sua semana',copy:'Uma base para adaptar',metric:'✦',rows:[['Manhã leve','08:00 · 3 passos'],['Movimento','18:00 · 20 min']]},
   day:{tag:'SEU DIA COM CLAREZA',title:'Bom dia, Aline',copy:'3 coisas importam hoje',metric:'3',rows:[['Enviar documento','10:00'],['Buscar encomenda','17:30']]}
 };
 const v=views[preview];const faqs=[['O Essence Life envia notificações?','Você cria lembretes para o horário que escolher, como água, remédios, consultas, tarefas e hábitos. Para receber os avisos, basta autorizar as notificações no seu dispositivo.'],['Como funciona a IA?','Nos recursos com IA, você descreve seu objetivo e recebe uma base personalizada para revisar, editar e adaptar. Ela não substitui profissionais de saúde.'],['É pagamento único?','Sim. Você escolhe seu plano, paga uma única vez e recebe acesso vitalício, sem mensalidade ou renovação automática.'],['Funciona no celular?','Sim. Você pode usar no navegador e instalar o Essence Life na tela inicial para abrir como um aplicativo.']];
 return <main className="landing landing-v2 care-landing">
  <header className="landing-header"><a className="landing-brand" href="/"><img src="/essence-life-logo.png" alt=""/><span>Essence Life</span></a><nav><a href="#como-ajuda">Como ajuda</a><a href="#recursos">Recursos</a><a href="#planos">Planos</a><button onClick={openApp}>Entrar</button></nav></header>
  <section className="landing-hero"><div className="landing-copy"><p className="landing-kicker">ROTINA REAL, APOIO DE VERDADE</p><h1>Sua cabeça não precisa ser o lugar onde tudo mora.</h1><p>Lembre de beber água, tomar um remédio, respirar, cumprir um compromisso e cuidar de você. O Essence Life organiza a sua rotina com leveza — e ajuda quando a correria faz tudo escapar.</p><div className="landing-actions"><button className="landing-primary" onClick={()=>document.getElementById('como-ajuda')?.scrollIntoView({behavior:'smooth'})}>Ver como o Essence ajuda</button><a href="#planos">Conhecer os planos <span>→</span></a></div><div className="landing-trust"><span>✦ Apoio inteligente</span><span>🔔 Lembretes personalizados</span><span>✓ Acesso vitalício</span></div></div><div className="landing-visual care-visual"><article className="visual-float"><small>HOJE, COM LEVEZA</small><b>Você não precisa lembrar de tudo.</b><div className="mini-progress"><i/></div></article><article className="visual-device"><div className="device-top"><span>10:42</span><b>Essence Life</b><span>☼</span></div><p>{v.tag}</p><h2>{v.title}</h2><div className="device-score"><strong>{v.metric}</strong><span>{v.copy}</span></div><div className="device-list">{v.rows.map(([a,b])=><div key={a}><i>✓</i><span><b>{a}</b><small>{b}</small></span></div>)}</div><footer><span>Hoje</span><span>Rotina</span><span>Cuidar</span></footer></article></div></section>
  <section id="como-ajuda" className="care-problem"><div><p className="landing-kicker">PARA OS DIAS CHEIOS</p><h2>A correria não deveria fazer você se esquecer de você.</h2><p>Quando a vida acelera, água, remédios, consultas, refeições, tarefas e descanso competem pela mesma memória. O Essence Life vira o seu espaço de apoio.</p></div><div className="care-problem-grid"><article><i>💧</i><b>“Já passou o dia e eu nem bebi água.”</b><span>Transforme cuidado em um lembrete possível.</span></article><article><i>💊</i><b>“Tenho medo de esquecer um horário importante.”</b><span>Crie avisos para o que precisa acontecer.</span></article><article><i>♡</i><b>“Eu cuido de tudo, menos de mim.”</b><span>Reserve espaço para o seu ritmo e bem-estar.</span></article></div></section>
  <section className="care-tools"><div className="care-tools-intro"><p className="landing-kicker">NA PRÁTICA</p><h2>Você escolhe o que quer lembrar. O Essence ajuda a sustentar.</h2><p>Toque em cada recurso para ver como ele entra na sua rotina.</p><div className="experience-tabs">{([['reminder','Lembretes'],['water','Bem-estar'],['ai','IA'],['day','Seu dia']] as const).map(([key,label])=><button className={preview===key?'active':''} onClick={()=>setPreview(key)} key={key}>{label}</button>)}</div></div><article className="experience-preview care-preview"><div className="preview-caption"><span>{v.tag}</span><b>{v.title}</b><small>{v.copy}</small></div><strong>{v.metric}</strong><div className="progress"><span style={{width:preview==='water'?'70%':preview==='ai'?'84%':preview==='day'?'56%':'66%'}}/></div>{v.rows.map(([a,b],i)=><div className="preview-row" key={a}><i>{i+1}</i><span><b>{a}</b><small>{b}</small></span><em>→</em></div>)}</article></section>
  <section id="recursos" className="module-tour"><div className="module-tour-intro"><p className="landing-kicker">TUDO EM UM SÓ LUGAR</p><h2>Menos aplicativos. Mais presença no seu dia.</h2><p>Comece pelo que você precisa agora e descubra os outros recursos no seu tempo.</p></div>{modules.map(group=><section className={'module-plan '+group.plan.toLowerCase()} key={group.plan}><div className="module-plan-head"><span>PLANO {group.plan.toUpperCase()}</span><h3>{group.headline}</h3><p>{group.plan==='Essencial'?'Para organizar o essencial com mais leveza.':'Para conectar bem-estar, planejamento e vida prática.'}</p></div><div className="module-grid">{group.items.map(([icon,title,copy])=><article key={title}><i>{icon}</i><div><h4>{title}</h4><p>{copy}</p></div></article>)}</div></section>)}</section>
  <section className="care-ai"><div><p className="landing-kicker">IA QUE AJUDA A COMEÇAR</p><h2>Quando faltar energia para planejar, comece com uma sugestão.</h2><p>Conte seu objetivo e receba uma base para rotina, treino, alimentação ou cuidados. Você revisa cada detalhe e decide o que faz sentido para a sua vida.</p><ul><li>Rotinas personalizadas para a semana</li><li>Treinos adaptados ao seu momento</li><li>Sugestões de alimentação e autocuidado</li></ul></div><aside><span>✦</span><small>NÃO É UMA ROTINA PRONTA</small><b>É um ponto de partida feito para você ajustar.</b><p>Sua realidade continua sendo a prioridade.</p></aside></section>
  <section id="planos" className="landing-plans lifetime-plans"><p className="landing-kicker">ACESSO VITALÍCIO</p><h2>Escolha o apoio que você quer ter por perto.</h2><p className="plans-lead">Pagamento único, sem mensalidade e com 7 dias de garantia.</p><div>{[{name:'Essencial',installment:'12x de R$ 5,66',cash:'ou R$ 67,90 à vista',from:'De R$ 127,90',copy:'Para organizar o essencial e lembrar de se cuidar.',features:['Lembretes, agenda, início e rotina','Água, sono, diário e ciclo','Acesso vitalício e atualizações']},{name:'Pro',installment:'12x de R$ 8,16',cash:'ou R$ 97,90 à vista',from:'De R$ 297,00',copy:'Para quem quer a experiência completa, com IA e todos os módulos.',features:['Tudo do plano Essencial','IA para rotina, treino e cuidados','Nutrição, finanças, casa e compras','Acesso completo a todos os módulos'],featured:true}].map(plan=><article className={plan.featured?'featured':''} key={plan.name}>{plan.featured&&<em>Mais escolhido</em>}<span className="plan-label">PLANO {plan.name.toUpperCase()}</span><h3>Essence Life — {plan.name}</h3><small className="plan-from">{plan.from}</small><strong>{plan.installment}</strong><b className="plan-cash">{plan.cash}</b><p>{plan.copy}</p><ul>{plan.features.map(item=><li key={item}>{item}</li>)}</ul><button onClick={()=>checkout(plan.name)}>Quero o {plan.name}</button></article>)}</div><p className="landing-note">🔒 Compra segura · Acesso liberado após a confirmação · 7 dias de garantia</p></section>
  <section className="landing-faq"><p className="landing-kicker">PERGUNTAS FREQUENTES</p><h2>Para começar com segurança.</h2><div>{faqs.map(([q,a],i)=><article key={q}><button onClick={()=>setOpenFaq(openFaq===i?null:i)} aria-expanded={openFaq===i}><span>{q}</span><b>{openFaq===i?'−':'+'}</b></button>{openFaq===i&&<p>{a}</p>}</article>)}</div></section>
  <section className="landing-final"><p className="landing-kicker">COMECE COM MAIS LEVEZA</p><h2>Você não precisa dar conta de tudo sozinha.</h2><p>Tenha um espaço para lembrar do que importa e voltar a se incluir na sua própria rotina.</p><button className="landing-primary" onClick={()=>document.getElementById('planos')?.scrollIntoView({behavior:'smooth'})}>Escolher meu plano</button></section><footer>© {new Date().getFullYear()} Essence Life <span>•</span> Leveza para a vida real.</footer>
 </main>;
}