import { useMemo, useState } from 'react';
import type { AppPage } from '../../shared/access-control';
import { readStoredArray } from '../../shared/storage';

type Dated={date:string};
type EnergyLevel='low'|'steady'|'high';
type Props={openPage:(page:AppPage)=>void};
const dateValue=(value:string)=>new Date(value+'T12:00:00').getTime();
const within=(date:string,start:number,end=Date.now())=>{const value=dateValue(date);return value>=start&&value<=end};
const sleepMinutes=(entry:{asleep?:string;wake?:string})=>{if(!entry.asleep||!entry.wake)return 0;const [ah,am]=entry.asleep.split(':').map(Number),[wh,wm]=entry.wake.split(':').map(Number);let minutes=wh*60+wm-(ah*60+am);if(minutes<0)minutes+=1440;return minutes};
const formatMinutes=(minutes:number)=>minutes?Math.floor(minutes/60)+'h '+String(minutes%60).padStart(2,'0'):'—';
const readEnergy=():Record<string,EnergyLevel>=>{try{return JSON.parse(localStorage.getItem('essence:daily-energy')||'{}')}catch{return {}}};

export default function Insights({openPage}:Props){
 const [range,setRange]=useState<7|30|90>(7);const [open,setOpen]=useState<string|null>('routine');
 const data=useMemo(()=>{const end=Date.now(),start=end-(range-1)*86400000,previousStart=start-range*86400000;
  const sleeps=readStoredArray<Dated&{asleep?:string;wake?:string}>('essence:sleeps'),routine=readStoredArray<Dated>('essence:routine-history'),workouts=readStoredArray<Dated&{seconds?:number}>('essence:workout-sessions'),diary=readStoredArray<Dated&{mood?:number}>('essence:diary'),water=readStoredArray<Dated&{ml?:number}>('essence:water-entries'),meals=readStoredArray<Dated>('essence:meals'),cycle=readStoredArray<Dated>('essence:cycle');
  const current=<T extends Dated,>(items:T[])=>items.filter(item=>within(item.date,start,end)),previous=<T extends Dated,>(items:T[])=>items.filter(item=>within(item.date,previousStart,start-1));
  const sleepNow=current(sleeps),sleepAvg=sleepNow.length?Math.round(sleepNow.reduce((sum,item)=>sum+sleepMinutes(item),0)/sleepNow.length):0,waterTotal=current(water).reduce((sum,item)=>sum+Number(item.ml||0),0),routineNow=current(routine),routineBefore=previous(routine),workoutNow=current(workouts),diaryNow=current(diary),mealNow=current(meals),cycleNow=current(cycle);
  const energyEntries=Object.entries(readEnergy()).filter(([date])=>within(date,start,end));
  const energyCounts=energyEntries.reduce((counts,[,level])=>({...counts,[level]:counts[level]+1}),{low:0,steady:0,high:0});
  const energyLevel=(Object.entries(energyCounts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'steady') as EnergyLevel;
  const energyLabel={low:'dias mais delicados',steady:'ritmo equilibrado',high:'boa disponibilidade'}[energyLevel];
  const total=routineNow.length+sleepNow.length+workoutNow.length+diaryNow.length+mealNow.length+cycleNow.length;
  const delta=routineNow.length-routineBefore.length;
  const focus=waterTotal===0?'Hidratação':sleepNow.length===0?'Sono':routineNow.length===0?'Rotina':diaryNow.length===0?'Uma pausa para você':'Manter o que já funciona';
  const cards=[
   {id:'routine',icon:'🗓️',title:'Rotina',value:routineNow.length+' conclusão(ões)',copy:routineNow.length?`Você registrou ${delta>=0?'mais ou o mesmo número de':'menos'} ações que no período anterior.`:'Conclua uma rotina para iniciar esta leitura.',next:'Escolha uma ação pequena para manter amanhã.',page:'routine' as AppPage},
   {id:'sleep',icon:'🌙',title:'Sono',value:sleepAvg?formatMinutes(sleepAvg)+' em média':'Sem média ainda',copy:sleepNow.length?`Média calculada a partir de ${sleepNow.length} noite(s).`:'Registre ao menos uma noite para acompanhar seu ritmo.',next:'Tente manter um horário possível para desacelerar.',page:'sleep' as AppPage},
   {id:'workouts',icon:'🏋️',title:'Treinos',value:workoutNow.length+' sessão(ões)',copy:workoutNow.length?'Seu movimento está aparecendo no histórico.':'Finalize um treino para acompanhar sua constância.',next:'Planeje uma sessão compatível com sua semana.',page:'workouts' as AppPage},
   {id:'nutrition',icon:'🥗',title:'Nutrição e hidratação',value:waterTotal?Math.round(waterTotal/100)/10+' L registrados':mealNow.length+' refeição(ões)',copy:`${mealNow.length} refeição(ões) e ${current(water).length} registro(s) de água no período.`,next:'Observe sua hidratação sem buscar perfeição.',page:'nutrition' as AppPage},
   {id:'diary',icon:'📘',title:'Diário',value:diaryNow.length+' registro(s)',copy:diaryNow.length?'Você reservou momentos para registrar como estava.':'Escreva quando sentir que pode ajudar.',next:'Uma frase sobre o dia já é suficiente.',page:'diary' as AppPage},
   {id:'cycle',icon:'🌸',title:'Ciclo',value:cycleNow.length+' registro(s)',copy:cycleNow.length?'Há informações para observar seu próprio padrão ao longo do tempo.':'Registre somente o que fizer sentido para você.',next:'Use os dados como referência pessoal, não diagnóstico.',page:'cycle' as AppPage},
  ];return{cards,total,delta,energyEntries:energyEntries.length,energyLabel,focus};
 },[range]);
 const focusPage:AppPage=data.focus==='Hidratação'?'nutrition':data.focus==='Sono'?'sleep':data.focus==='Rotina'?'routine':data.focus==='Uma pausa para você'?'diary':'home';
 return <section className="insights-module"><article className="insights-hero"><div><small>SEU RITMO EM UM SÓ LUGAR</small><h3>Insights integrados</h3><p>Observe tendências dos seus próprios registros, com leveza e sem diagnósticos.</p></div><span>✨</span></article><article className="card insights-summary"><div><small>VISÃO DOS ÚLTIMOS {range} DIAS</small><h3>{data.total} registro(s) conectados</h3><p>{data.total?'Abra cada área para entender o que seus registros mostram.':'Continue usando os módulos para construir sua visão integrada.'}</p></div><div className="insights-range">{([7,30,90] as const).map(value=><button type="button" className={range===value?'active':''} onClick={()=>setRange(value)} key={value}>{value} dias</button>)}</div></article><article className="card insights-weekly-review"><div className="insights-review-title"><span>🌷</span><div><small>SUA REVISÃO DO PERÍODO</small><h3>O que sua semana está contando</h3></div></div><div className="insights-review-metrics"><div><b>{data.total}</b><span>registros de cuidado</span></div><div><b>{data.delta>=0?'+'+data.delta:data.delta}</b><span>ações vs. período anterior</span></div><div><b>{data.energyEntries||'—'}</b><span>check-ins de energia</span></div></div><p>{data.energyEntries?`Seu check-in mostrou ${data.energyLabel}. O app usa essa percepção para sugerir passos mais compatíveis com você.`:'Faça o check-in de energia na tela inicial para deixar as próximas leituras mais pessoais.'}</p><div className="insights-review-focus"><span>PRÓXIMO FOCO POSSÍVEL</span><b>{data.focus}</b><button type="button" onClick={()=>openPage(focusPage)}>Começar com leveza</button></div></article><div className="insights-grid">{data.cards.map(card=>{const opened=open===card.id;return <article className={'card insights-card '+(opened?'open':'')} key={card.id}><button type="button" className="insights-card-head" aria-expanded={opened} onClick={()=>setOpen(opened?null:card.id)}><span>{card.icon}</span><div><small>{card.title.toUpperCase()}</small><h3>{card.value}</h3></div><strong>{opened?'−':'+'}</strong></button>{opened&&<div className="insights-card-body"><p>{card.copy}</p><div><small>PRÓXIMO PASSO POSSÍVEL</small><b>{card.next}</b></div><button type="button" onClick={()=>openPage(card.page)}>Abrir {card.title}</button></div>}</article>})}</div><article className="insights-disclaimer"><b>Leitura de bem-estar</b><p>Estes insights resumem associações simples dos seus registros. Não representam diagnóstico, previsão clínica ou orientação profissional.</p></article></section>;
}