import './CycleHistory.css';

type Entry={id:string;date:string;flow:string;moods?:string[];mood?:string;symptoms:string[]};
type Props={monthDate:Date;days:number;offset:number;entries:Entry[];recorded:Map<string,Entry>;calendarMonth:string;isPredicted:(date:string)=>boolean;onPrevious:()=>void;onNext:()=>void;onOpen:(date:string)=>void;cycleLength:number};

export default function CycleHistory({monthDate,days,offset,entries,recorded,calendarMonth,isPredicted,onPrevious,onNext,onOpen,cycleLength}:Props){
 const label=new Intl.DateTimeFormat('pt-BR',{month:'long',year:'numeric'}).format(monthDate);
 const recent=[...entries].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3);
 return <section className="cycle-history-view"><header><h2>Seu histórico do ciclo</h2><p>Acompanhe seus registros e veja como seu ciclo vem se comportando.</p></header><article className="cycle-history-calendar"><div className="cycle-history-month"><button onClick={onPrevious} aria-label="Mês anterior">‹</button><h3>{label}</h3><button onClick={onNext} aria-label="Próximo mês">›</button></div><div className="cycle-history-week">{['DOM','SEG','TER','QUA','QUI','SEX','SÁB'].map(day=><b key={day}>{day}</b>)}</div><div className="cycle-history-days">{Array.from({length:offset},(_,i)=><span key={'e'+i}/>)}{Array.from({length:days},(_,i)=>{const day=i+1,date=`${calendarMonth}-${String(day).padStart(2,'0')}`,entry=recorded.get(date);return <button key={date} className={`${entry?'recorded ':''}${isPredicted(date)?'predicted':''}`} onClick={()=>onOpen(date)}>{day}{entry&&<i/>}</button>})}</div><div className="cycle-history-legend"><span><i className="period"/>Menstruação</span><span><i className="fertile"/>Período fértil</span><span><i className="ovulation"/>Ovulação</span><span><i className="record"/>Registro completo</span></div></article><article className="cycle-history-records"><div><h3>Últimos registros</h3><button>Ver todos ›</button></div>{recent.length?recent.map(entry=><button className="cycle-history-row" key={entry.id} onClick={()=>onOpen(entry.date)}><time>{new Intl.DateTimeFormat('pt-BR',{day:'2-digit',month:'short'}).format(new Date(entry.date+'T12:00:00'))}</time><span className="drop">●</span><span><b>{entry.flow==='Sem fluxo'?'Registro do ciclo':entry.flow==='Leve'||entry.flow==='Moderado'||entry.flow==='Intenso'?'Menstruação':entry.flow}</b><small>{[...(entry.moods||[]),...entry.symptoms].filter(Boolean).join(' · ')||'Detalhes registrados'}</small></span><em>›</em></button>):<p>Seus registros aparecerão aqui.</p>}</article><article className="cycle-history-summary"><div><h3>Resumo do seu ciclo</h3><small>Últimos ciclos</small></div><section><span>▣<b>Duração média<strong>{cycleLength} dias</strong></b></span><span>●<b>Menstruação<strong>5 dias</strong></b></span><span>↻<b>Regularidade<strong>Ciclo regular</strong></b></span></section><p>🌿 Seu ciclo tem se mantido regular nos últimos meses.</p></article></section>
}
