/* oxlint-disable no-unused-vars -- concatenated into the generated Sites worker */
async function handleApi(request,env){
  const url=new URL(request.url);
  const pushResponse=await handlePushApi(request,env,url);if(pushResponse)return pushResponse;
const fs=require('fs');const p='worker/api.js';let s=fs.readFileSync(p,'utf8');if(!s.includes('/api/mental/organize')){const b=Buffer.from(process.argv[1],'hex').toString();const m="  if(url.pathname==='/api/nutrition/menu'){";s=s.replace(m,b+String.fromCharCode(10)+m);fs.writeFileSync(p,s)}
  if(url.pathname==='/api/nutrition/menu'){
    if(request.method!=='POST')return new Response('Method not allowed',{status:405});
    if(!env.OPENAI_API_KEY)return Response.json({error:'A geração com IA ainda não está configurada.'},{status:503});
    let body;try{body=await request.json()}catch{return Response.json({error:'Dados inválidos.'},{status:400})}
    const goal=String(body?.goal||'Saúde e bem-estar').slice(0,80);
    const restrictions=String(body?.restrictions||'Nenhuma informada').slice(0,500);
    const meals=Math.max(3,Math.min(6,Number(body?.meals)||3));
    const days=Math.max(1,Math.min(3,Number(body?.days)||1));
    const extra=String(body?.extra||'').slice(0,300);
    const clinical=/diabet|renal|rim|gesta|grávid|gravidez|transtorno alimentar|anorex|bulimi|alergia grave|anafilax/i.test(restrictions+' '+extra);
    if(clinical)return Response.json({error:'Para condições clínicas, gestação, transtornos alimentares ou alergias graves, procure orientação de nutricionista ou médico antes de gerar sugestões.'},{status:422});
    const prompt=`Crie sugestões alimentares gerais, variadas, simples e acessíveis em português do Brasil. Objetivo declarado: ${goal}. Refeições por dia: ${meals}. Dias: ${days}. Preferências, restrições ou alergias declaradas: ${restrictions}. Contexto opcional: ${extra||'nenhum'}. Não prescreva tratamento, calorias, macros, suplementos, dietas extremas ou perda rápida de peso. Respeite rigorosamente as restrições declaradas. Responda SOMENTE JSON válido neste formato: {"summary":"texto curto","items":[{"day":1,"mealType":"Café da manhã","title":"nome curto","ingredients":["item 1","item 2"],"note":"troca ou preparo curto"}]}. Gere exatamente ${meals*days} itens.`;
    const ai=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:'gpt-5-mini',input:prompt,reasoning:{effort:'low'},text:{verbosity:'low'},max_output_tokens:3000})});
    if(!ai.ok){const status=ai.status===429?429:502;return Response.json({error:ai.status===429?'Muitas solicitações agora. Aguarde um pouco e tente novamente.':'Não foi possível gerar as sugestões agora.'},{status})}
    const result=await ai.json();
    const output=String(result.output_text||result.output?.flatMap(item=>item.content||[]).find(item=>item.type==='output_text')?.text||'').trim().replace(/^```json\s*/i,'').replace(/```$/,'').trim();
    let menu;try{menu=JSON.parse(output)}catch{return Response.json({error:'A IA retornou um formato inesperado. Tente novamente.'},{status:502})}
    if(!Array.isArray(menu.items)||!menu.items.length)return Response.json({error:'Nenhuma sugestão foi gerada. Tente novamente.'},{status:502});
    const items=menu.items.slice(0,18).map((item,index)=>({id:`ai-${Date.now()}-${index}`,day:Math.max(1,Math.min(days,Number(item.day)||1)),mealType:String(item.mealType||'Refeição').slice(0,40),title:String(item.title||'Sugestão').slice(0,100),ingredients:(Array.isArray(item.ingredients)?item.ingredients:[]).map(value=>String(value).slice(0,80)).slice(0,12),note:String(item.note||'').slice(0,160)}));
    return Response.json({summary:String(menu.summary||'Sugestões criadas para você adaptar à sua rotina.').slice(0,220),items});
  }
  if(url.pathname==='/api/routine/generate'){
    if(request.method!=='POST')return new Response('Method not allowed',{status:405});if(!env.OPENAI_API_KEY)return Response.json({error:'A geração inteligente ainda não está configurada.'},{status:503});let body;try{body=await request.json()}catch{return Response.json({error:'Dados inválidos.'},{status:400})}
    const goal=String(body?.goal||'Uma semana equilibrada').slice(0,180),wake=String(body?.wake||'07:00').slice(0,5),sleep=String(body?.sleep||'22:30').slice(0,5),priorities=String(body?.priorities||'Bem-estar').slice(0,300),modules=(Array.isArray(body?.modules)?body.modules:[]).map(String).slice(0,8),busy=(Array.isArray(body?.busy)?body.busy:[]).map(String).slice(0,40);
    const prompt=`Monte uma rotina semanal realista em português do Brasil. Objetivo: ${goal}. Acorda: ${wake}. Dorme: ${sleep}. Prioridades: ${priorities}. Áreas para integrar: ${modules.join(', ')||'bem-estar'}. Horários já ocupados na agenda: ${busy.join(', ')||'nenhum informado'}. Não sobrecarregue: no máximo 4 ações por dia, duração de 10 a 60 minutos, respeite sono e evite conflitos. Responda SOMENTE JSON: {"summary":"texto curto","groups":[{"day":"SEG","items":[{"name":"ação","time":"08:00","category":"Saúde","duration":"00:20","notes":"orientação curta"}]}]}. Dias permitidos: SEG, TER, QUA, QUI, SEX, SÁB, DOM. Categorias: Pessoal, Saúde, Trabalho, Casa, Estudos.`;
    const ai=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:'gpt-5-mini',input:prompt,reasoning:{effort:'low'},text:{verbosity:'low'},max_output_tokens:3200})});
    if(!ai.ok){const templates=[{name:'Planejar as prioridades do dia',time:'08:00',category:'Pessoal',duration:'00:10',notes:'Escolha até três prioridades possíveis.'},{name:'Pausa para movimento',time:'12:30',category:'Saúde',duration:'00:20',notes:'Movimente-se no seu ritmo.'},{name:'Organizar um pequeno espaço',time:'18:30',category:'Casa',duration:'00:15',notes:'Escolha apenas uma área.'},{name:'Preparar o descanso',time:'21:30',category:'Saúde',duration:'00:20',notes:'Reduza estímulos e desacelere.'}],codes=['SEG','TER','QUA','QUI','SEX','SÁB','DOM'],groups=codes.map((day,index)=>({day,items:templates.filter((_,i)=>i===0||i===3||(index+i)%3===0).map((item,i)=>({...item,id:`smart-routine-${Date.now()}-${index}-${i}`,days:[day],reminderEnabled:false,reminderTime:item.time,done:false}))}));return Response.json({summary:'A IA está temporariamente indisponível. Criamos uma semana-base leve, sem substituir seus compromissos atuais.',groups,fallback:true})}
    const result=await ai.json(),output=String(result.output_text||result.output?.flatMap(item=>item.content||[]).find(item=>item.type==='output_text')?.text||'').trim().replace(/^```json\s*/i,'').replace(/```$/,'').trim();let generated;try{generated=JSON.parse(output)}catch{return Response.json({error:'A IA retornou um formato inesperado. Tente novamente.'},{status:502})}const allowedDays=['SEG','TER','QUA','QUI','SEX','SÁB','DOM'],allowedCategories=['Pessoal','Saúde','Trabalho','Casa','Estudos'];if(!Array.isArray(generated.groups))return Response.json({error:'Nenhuma rotina foi gerada.'},{status:502});const groups=generated.groups.slice(0,7).map((group,g)=>{const day=allowedDays.includes(group.day)?group.day:allowedDays[g];return{day,items:(Array.isArray(group.items)?group.items:[]).slice(0,4).map((item,i)=>({id:`ai-routine-${Date.now()}-${g}-${i}`,name:String(item.name||'Nova ação').slice(0,90),time:String(item.time||'08:00').slice(0,5),category:allowedCategories.includes(item.category)?item.category:'Pessoal',duration:String(item.duration||'00:20').slice(0,5),notes:String(item.notes||'').slice(0,150),days:[day],reminderEnabled:false,reminderTime:String(item.time||'08:00').slice(0,5),done:false}))}});return Response.json({summary:String(generated.summary||'Revise a semana e salve apenas o que fizer sentido.').slice(0,220),groups});
  }
  if(url.pathname==='/api/beauty/generate'){
    if(request.method!=='POST')return new Response('Method not allowed',{status:405});
    if(!env.OPENAI_API_KEY)return Response.json({error:'A geração personalizada ainda não está configurada.'},{status:503});
    let body;try{body=await request.json()}catch{return Response.json({error:'Dados inválidos.'},{status:400})}
    const skin=String(body?.skin||'Não informado').slice(0,80),hair=String(body?.hair||'Não informado').slice(0,80),goals=String(body?.goals||'Cuidados essenciais').slice(0,250),products=String(body?.products||'Nenhum informado').slice(0,350),sensitivities=String(body?.sensitivities||'Nenhuma informada').slice(0,400);
    if(/ferida|infecção|infeccao|alergia grave|queda intensa|queimadura|lesão|lesao|dor intensa/i.test(sensitivities))return Response.json({error:'Para sintomas intensos, feridas ou alergias importantes, procure avaliação dermatológica antes de criar uma rotina.'},{status:422});
    const prompt=`Crie uma rotina simples de autocuidado em português do Brasil. Pele: ${skin}. Cabelo: ${hair}. Objetivos: ${goals}. Produtos disponíveis: ${products}. Sensibilidades: ${sensitivities}. Não faça diagnóstico, não prescreva medicamentos, ácidos, concentrações ou procedimentos. Priorize limpeza suave, hidratação, proteção solar e cuidados capilares gentis. Responda SOMENTE JSON: {"summary":"texto curto","groups":[{"title":"Manhã","items":[{"title":"cuidado","category":"Skincare","time":"08:00","period":"Manhã","frequency":"Diário"}]}]}. Categorias permitidas: Skincare, Cabelo, Corpo, Unhas. Gere 2 a 4 grupos e no máximo 12 itens.`;
    const ai=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:'gpt-5-mini',input:prompt,reasoning:{effort:'low'},text:{verbosity:'low'},max_output_tokens:2600})});
    if(!ai.ok){const groups=[{title:'Manhã',items:[{title:'Limpeza suave do rosto',category:'Skincare',time:'08:00',period:'Manhã',frequency:'Diário'},{title:'Hidratação confortável',category:'Skincare',time:'08:05',period:'Manhã',frequency:'Diário'},{title:'Proteção solar',category:'Skincare',time:'08:10',period:'Manhã',frequency:'Diário'}]},{title:'Noite',items:[{title:'Remover resíduos e maquiagem',category:'Skincare',time:'21:30',period:'Noite',frequency:'Diário'},{title:'Hidratação noturna',category:'Skincare',time:'21:35',period:'Noite',frequency:'Diário'}]},{title:'Cuidados semanais',items:[{title:'Hidratação dos cabelos',category:'Cabelo',time:'19:00',period:'Qualquer horário',frequency:'Semanal'},{title:'Hidratação corporal',category:'Corpo',time:'20:30',period:'Noite',frequency:'Dias alternados'}]}];return Response.json({summary:'A IA está temporariamente indisponível. Criamos uma base automática e delicada para você revisar.',groups,fallback:true})}
    const result=await ai.json(),output=String(result.output_text||result.output?.flatMap(item=>item.content||[]).find(item=>item.type==='output_text')?.text||'').trim().replace(/^```json\s*/i,'').replace(/```$/,'').trim();let generated;try{generated=JSON.parse(output)}catch{return Response.json({error:'A IA retornou um formato inesperado. Tente novamente.'},{status:502})}if(!Array.isArray(generated.groups))return Response.json({error:'Nenhuma rotina foi gerada.'},{status:502});
    const allowed=['Skincare','Cabelo','Corpo','Unhas'],groups=generated.groups.slice(0,4).map((group,g)=>({title:String(group.title||`Grupo ${g+1}`).slice(0,50),items:(Array.isArray(group.items)?group.items:[]).slice(0,6).map((item,i)=>({id:`ai-beauty-${Date.now()}-${g}-${i}`,title:String(item.title||'Cuidado').slice(0,90),category:allowed.includes(item.category)?item.category:'Skincare',time:String(item.time||'08:00').slice(0,5),period:String(item.period||group.title||'Qualquer horário').slice(0,30),frequency:String(item.frequency||'Diário').slice(0,30),reminderEnabled:false,reminderTime:String(item.time||'08:00').slice(0,5)}))}));return Response.json({summary:String(generated.summary||'Revise e adapte sua rotina antes de salvar.').slice(0,220),groups});
  }
  if(url.pathname==='/api/workouts/generate'){
    if(request.method!=='POST')return new Response('Method not allowed',{status:405});
    if(!env.OPENAI_API_KEY)return Response.json({error:'A geração com IA ainda não está configurada.'},{status:503});
    let body;try{body=await request.json()}catch{return Response.json({error:'Dados inválidos.'},{status:400})}
    const goal=String(body?.goal||'Saúde e bem-estar').slice(0,80),level=String(body?.level||'Iniciante').slice(0,40),location=String(body?.location||'Casa').slice(0,60),equipment=String(body?.equipment||'Nenhum').slice(0,300),limitations=String(body?.limitations||'Nenhuma informada').slice(0,500);
    const days=Math.max(1,Math.min(5,Number(body?.days)||3)),duration=Math.max(10,Math.min(90,Number(body?.duration)||30));
    if(/dor (intensa|aguda)|lesão|lesao|cirurgia|gesta|grávid|gravidez|cardíac|cardiac|desmaio|falta de ar|hérnia|hernia/i.test(limitations))return Response.json({error:'Para dor, lesão, gestação ou condição clínica, procure orientação profissional antes de gerar um treino.'},{status:422});
    const prompt=`Crie uma sugestão semanal de treino geral em português do Brasil. Objetivo: ${goal}. Nível: ${level}. Local: ${location}. Equipamentos: ${equipment}. Frequência: ${days} dia(s) por semana. Duração por sessão: ${duration} minutos. Limitações declaradas: ${limitations}. Seja conservador, evite cargas prescritas, movimentos de alto risco e linguagem médica. Inclua aquecimento e volta à calma. Responda SOMENTE JSON válido: {"summary":"aviso curto","plans":[{"name":"nome","goal":"objetivo","duration":30,"exercises":[{"name":"exercício","sets":"3","reps":"8-12 ou 30 segundos","load":"leve ou peso corporal"}]}]}. Gere exatamente ${days} planos diferentes, com 5 a 8 exercícios cada.`;
    const ai=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${env.OPENAI_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({model:'gpt-5-mini',input:prompt,reasoning:{effort:'low'},text:{verbosity:'low'},max_output_tokens:3500})});
    if(!ai.ok){
      const home=['Marcha estacionária','Agachamento no ritmo confortável','Flexão na parede','Elevação pélvica','Remada com elástico ou toalha','Prancha com joelhos apoiados','Alongamento leve'],gym=['Caminhada leve','Agachamento guiado','Remada sentada','Supino na máquina','Elevação pélvica','Puxada frontal','Alongamento leve'],outdoor=['Caminhada leve','Agachamento em banco','Subida em degrau baixo','Remada com elástico','Elevação de panturrilhas','Prancha inclinada','Alongamento leve'],base=location==='Academia'?gym:location==='Ao ar livre'?outdoor:home;
      const plans=Array.from({length:days},(_,index)=>({id:`smart-workout-${Date.now()}-${index}`,name:`${goal} · Dia ${index+1}`,goal,duration,done:false,exercises:base.slice(index%2,Math.min(base.length,index%2+6)).map((name,exerciseIndex)=>({id:`smart-exercise-${Date.now()}-${index}-${exerciseIndex}`,name,sets:exerciseIndex===0||exerciseIndex===5?'2':'3',reps:exerciseIndex===0?'3-5 minutos':exerciseIndex===5?'30 segundos':'8-12',load:level==='Iniciante'?'Leve ou peso corporal':'Carga confortável'}))}));
      return Response.json({summary:'A IA está temporariamente indisponível. Criamos uma base automática segura para você revisar e adaptar antes de salvar.',plans,fallback:true});
    }
    const result=await ai.json(),output=String(result.output_text||result.output?.flatMap(item=>item.content||[]).find(item=>item.type==='output_text')?.text||'').trim().replace(/^```json\s*/i,'').replace(/```$/,'').trim();
    let generated;try{generated=JSON.parse(output)}catch{return Response.json({error:'A IA retornou um formato inesperado. Tente novamente.'},{status:502})}
    if(!Array.isArray(generated.plans)||!generated.plans.length)return Response.json({error:'Nenhum treino foi gerado. Tente novamente.'},{status:502});
    const plans=generated.plans.slice(0,days).map((plan,index)=>({id:`ai-workout-${Date.now()}-${index}`,name:String(plan.name||`Treino ${index+1}`).slice(0,80),goal:String(plan.goal||goal).slice(0,60),duration:Math.max(10,Math.min(90,Number(plan.duration)||duration)),done:false,exercises:(Array.isArray(plan.exercises)?plan.exercises:[]).slice(0,10).map((exercise,exerciseIndex)=>({id:`ai-exercise-${Date.now()}-${index}-${exerciseIndex}`,name:String(exercise.name||'Exercício').slice(0,90),sets:String(exercise.sets||'3').slice(0,20),reps:String(exercise.reps||'8-12').slice(0,30),load:String(exercise.load||'Peso corporal').slice(0,50)}))}));
    return Response.json({summary:String(generated.summary||'Revise e adapte as sugestões antes de começar.').slice(0,240),plans});
  }
  if(url.pathname!=='/api/kiwify/webhook')return null;
  if(request.method!=='POST')return new Response('Method not allowed',{status:405});
  const supplied=url.searchParams.get('token')||request.headers.get('x-webhook-secret')||'';
  if(!env.KIWIFY_WEBHOOK_SECRET||supplied!==env.KIWIFY_WEBHOOK_SECRET)return new Response('Unauthorized',{status:401});
  if(!env.SUPABASE_SECRET_KEY||!env.SUPABASE_URL)return new Response('Integration not configured',{status:503});
  let payload;try{payload=await request.json()}catch{return new Response('Invalid JSON',{status:400})}
  const customer=payload.Customer||payload.customer||payload.buyer||{};
  const product=payload.Product||payload.product||{};
  const email=String(customer.email||payload.customer_email||payload.email||'').trim().toLowerCase();
  const productName=String(product.product_name||product.name||payload.product_name||'');
  const event=String(payload.webhook_event_type||payload.event_type||payload.order_status||payload.status||'').toLowerCase();
  const transactionId=String(payload.order_id||payload.transaction_id||payload.id||'');
  if(!email||!email.includes('@'))return new Response('Customer email missing',{status:422});
  const normalized=productName.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const plan=normalized.includes('pro')?'pro':normalized.includes('essencial')?'essential':null;
  if(!plan)return new Response('Unknown product',{status:422});
  const revoked=/refund|refunded|chargeback|chargedback|reembolso/.test(event);
  const approved=/approved|paid|complete|aprovad|pago/.test(event);
  if(!approved&&!revoked)return new Response('Event ignored',{status:200});
  const response=await fetch(`${env.SUPABASE_URL}/rest/v1/entitlements?on_conflict=email`,{method:'POST',headers:{apikey:env.SUPABASE_SECRET_KEY,'user-agent':'essence-life-server/1.0','content-type':'application/json',prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({email,plan,status:revoked?'revoked':'active',transaction_id:transactionId||null,product_name:productName,updated_at:new Date().toISOString()})});
  if(!response.ok)return new Response('Could not update entitlement',{status:502});
  return new Response('ok',{status:200});
}
