import { useEffect, useMemo, useRef, useState } from 'react';
import type { Dispatch, SetStateAction } from 'react';
import type { LocalSession } from '../../shared/app.types';
import type { AppPage } from '../../shared/access-control';
import { createId as id, greeting, today } from '../../shared/app-utils';
import { requestReminderPermission, syncAppReminder, syncDatedReminder } from '../../shared/reminders';

type HomeTask={id:string;title:string;date:string;time?:string;category?:string;priority:string;reminderEnabled?:boolean;reminderTime?:string;done:boolean};
type HomeHabit={id:string;name:string;time:string;category:string;days:string[];reminderEnabled?:boolean;reminderTime?:string;done:boolean;doneDate?:string};
type QuickCreate='task'|'habit'|null;
type EnergyLevel='low'|'steady'|'high';
type HomeProps={session:LocalSession;pendingHabits:HomeHabit[];pendingTasks:HomeTask[];completedHabits:HomeHabit[];completedTasks:HomeTask[];totalToday:number;completedToday:number;dayProgress:number;waterToday:number;quickCreate:QuickCreate;setQuickCreate:Dispatch<SetStateAction<QuickCreate>>;openPage:(page:AppPage)=>void;registerHomeWater:()=>number;unregisterHomeWater:()=>number;completeHomeHabit:(habitId:string)=>void;completeHomeTask:(taskId:string)=>void;setHomeTasks:Dispatch<SetStateAction<HomeTask[]>>;setHomeHabits:Dispatch<SetStateAction<HomeHabit[]>>};

const read=<T,>(key:string,fallback:T):T=>{try{return JSON.parse(localStorage.getItem(key)||'') as T}catch{return fallback}};
const categoryIcon=(category:string,title:string)=>{
const text=`${category} ${title}`.toLowerCase();
if(text.includes('água')||text.includes('agua')||text.includes('hidrata'))return '💧';
if(text.includes('remédio')||text.includes('remedio')||text.includes('medica')||text.includes('venlafaxina'))return '💊';
if(text.includes('treino'))return '🏋️';
if(text.includes('caminhar')||text.includes('caminhada'))return '🚶';
return ({'saúde':'🩺','bem-estar':'🌿','treinos':'🏋️','casa':'🏠','trabalho':'💼','estudos':'📚','nutrição':'🥗','sono':'🌙','finanças':'💰','beleza':'🪞','pessoal':'✨'}[category.toLowerCase()]||'✓');
};
function Home({session,pendingHabits,pendingTasks,completedHabits,completedTasks,totalToday,completedToday,dayProgress,waterToday,quickCreate,setQuickCreate,openPage,registerHomeWater,unregisterHomeWater,completeHomeHabit,completeHomeTask,setHomeTasks,setHomeHabits}:HomeProps){
const [notice,setNotice]=useState('');
const [energy,setEnergy]=useState<EnergyLevel>(()=>read<Record<string,EnergyLevel>>('essence:daily-energy',{})[today()]||'steady');
const quickCreateRef=useRef<HTMLElement|null>(null);
useEffect(()=>{if(!quickCreate)return;const revealTitle=()=>{const title=quickCreateRef.current?.querySelector<HTMLInputElement>('input[name="title"]');quickCreateRef.current?.scrollIntoView({behavior:'smooth',block:'start'});title?.focus({preventScroll:true});title?.scrollIntoView({behavior:'smooth',block:'center'})};const timers=[0,360,850].map(delay=>window.setTimeout(revealTitle,delay));window.visualViewport?.addEventListener('resize',revealTitle);return()=>{timers.forEach(window.clearTimeout);window.visualViewport?.removeEventListener('resize',revealTitle)}},[quickCreate]);
const showNotice=(message:string)=>{setNotice(message);window.setTimeout(()=>setNotice(''),2600)};
const timeline=useMemo(()=>[...pendingTasks.map(item=>({id:item.id,title:item.title,time:item.time||'',category:item.category||'Pessoal',kind:'task' as const,done:false})),...pendingHabits.map(item=>({id:item.id,title:item.name,time:item.time||'',category:item.category||'Pessoal',kind:'habit' as const,done:false})),...completedTasks.map(item=>({id:item.id,title:item.title,time:item.time||'',category:item.category||'Pessoal',kind:'task' as const,done:true})),...completedHabits.map(item=>({id:item.id,title:item.name,time:item.time||'',category:item.category||'Pessoal',kind:'habit' as const,done:true}))].sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99')),[pendingTasks,pendingHabits,completedTasks,completedHabits]);
const pendingCount=pendingTasks.length+pendingHabits.length;
const sleep=[...read<{date:string;quality?:number;asleep?:string;wake?:string}[]>('essence:sleeps',[])].sort((a,b)=>b.date.localeCompare(a.date))[0];
const diaryCount=read<{date:string}[]>('essence:diary',[]).filter(entry=>entry.date===today()).length;
const workoutCount=read<{date:string}[]>('essence:workout-sessions',[]).filter(entry=>entry.date===today()).length;
const nextTask=[...pendingTasks].sort((a,b)=>{
const weight=(priority:string)=>priority.toLowerCase()==='alta'?0:priority.toLowerCase()==='baixa'?2:1;
const energyWeight=(priority:string)=>energy==='low'?-weight(priority):energy==='high'?weight(priority):0;
return energyWeight(a.priority)-energyWeight(b.priority)||(a.time||'99:99').localeCompare(b.time||'99:99');
})[0];
const energyCopy={
low:{title:'Hoje está mais difícil',text:'Vamos reduzir a pressão e cuidar apenas do próximo passo possível.'},
steady:{title:'No seu ritmo',text:'Seu planejamento continua leve e pode ser ajustado ao longo do dia.'},
high:{title:'Você está com energia',text:'Aproveite o momento para adiantar uma prioridade sem sobrecarregar o restante do dia.'}
}[energy];
const careSuggestion=waterToday<750
?{icon:'💧',title:'Um copo de água',copy:'Um registro rápido para cuidar da hidratação.',action:()=>{const total=registerHomeWater();showNotice('Água registrada · '+total+' ml hoje')}}
:!sleep
?{icon:'🌙',title:'Registrar seu sono',copy:'Ajuda o Essence a entender melhor o seu ritmo.',action:()=>openPage('sleep')}
:diaryCount===0&&energy==='low'
?{icon:'📘',title:'Uma pausa no diário',copy:'Uma frase já pode aliviar o que está na cabeça.',action:()=>openPage('diary')}
:{icon:'🌿',title:'Cuidar sem pressão',copy:'Mantenha apenas o próximo passo que fizer sentido.',action:()=>openPage('agenda')};
const updateEnergy=(level:EnergyLevel)=>{setEnergy(level);const history=read<Record<string,EnergyLevel>>('essence:daily-energy',{});localStorage.setItem('essence:daily-energy',JSON.stringify({...history,[today()]:level}));showNotice('Ritmo do dia atualizado')};
const dateLabel=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'numeric',month:'long'}).format(new Date());
return <section className="home home-v2">
<article className="hero home-dashboard-hero"><div className="home-welcome"><small>{dateLabel}</small><h3>{greeting()}, {session.name}!</h3><p>{totalToday?<>Você concluiu <b>{completedToday} de {totalToday}</b> ações de hoje.</>:'Seu dia está livre. Escolha um pequeno passo para começar.'}</p></div><div className="home-progress-ring" style={{'--progress':`${dayProgress}%`} as React.CSSProperties}><span><strong>{dayProgress}%</strong><small>do dia</small></span><div className="home-progress-track"><i style={{width:dayProgress+'%'}}/></div></div><div className="home-next"><small>PRÓXIMO PASSO</small><b>{nextTask?.title||timeline[0]?.title||'Planejar com leveza'}</b><span>{nextTask?.time||timeline[0]?.time||'No seu ritmo'}</span><button className="primary" onClick={()=>openPage('agenda')}>Ver meu dia</button></div></article>
{notice&&<div className="agenda-toast home-toast" role="status">✓ {notice}</div>}
<article className="card home-energy-checkin">
<div><span className="quick-actions-kicker">SEU RITMO IMPORTA</span><h3>Como você se sente hoje?</h3><p>O Essence adapta as sugestões ao seu momento.</p></div>
<div className="home-energy-options" role="group" aria-label="Energia de hoje">
<button type="button" className={energy==='low'?'active':''} onClick={()=>updateEnergy('low')}><span>🌿</span>Pouca energia</button>
<button type="button" className={energy==='steady'?'active':''} onClick={()=>updateEnergy('steady')}><span>☀️</span>No meu ritmo</button>
<button type="button" className={energy==='high'?'active':''} onClick={()=>updateEnergy('high')}><span>✨</span>Com energia</button>
</div>
<div className="home-energy-guidance"><div><b>{energyCopy.title}</b><span>{energyCopy.text}</span></div>{nextTask&&<button type="button" onClick={()=>openPage('agenda')}>Próximo: {nextTask.title}</button>}</div>
<div className="home-adaptive-plan"><div><span>{careSuggestion.icon}</span><div><small>SUGESTÃO PARA O SEU MOMENTO</small><b>{careSuggestion.title}</b><p>{careSuggestion.copy}</p></div></div><button type="button" onClick={careSuggestion.action}>Fazer agora</button></div>
</article>
<article className="card quick-actions"><div className="card-head quick-actions-head"><div><span className="quick-actions-kicker">ATALHOS DO DIA</span><h3>Ações rápidas</h3><p>Registre o que importa sem interromper seu momento.</p></div></div><div className="quick-actions-grid"><button type="button" onClick={()=>setQuickCreate('task')}><span>＋</span><b>Nova tarefa</b></button><button type="button" onClick={()=>setQuickCreate('habit')}><span>✦</span><b>Novo hábito</b></button><button type="button" onClick={()=>{const total=registerHomeWater();showNotice(`Água registrada · ${total} ml hoje`)}}><span>💧</span><b>+ 250 ml de água</b></button><button type="button" onClick={()=>openPage('diary')}><span>✎</span><b>Escrever no diário</b></button></div></article>
{quickCreate&&<article ref={quickCreateRef} className="card quick-create" tabIndex={-1}><div className="card-head"><div><h3>{quickCreate==='task'?'Nova tarefa':'Novo hábito'}</h3><p>{quickCreate==='task'?'Adicione uma ação para hoje.':'Crie um hábito simples para começar hoje.'}</p></div><button type="button" onClick={()=>setQuickCreate(null)}>Fechar</button></div><form className="form" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);const title=String(form.get('title')||'').trim();if(!title)return;const reminderEnabled=form.get('reminderEnabled')==='on',reminderTime=String(form.get('reminderTime')||form.get('time')||'09:00');if(quickCreate==='task'){const entry={id:id(),title,date:today(),time:String(form.get('time')||''),category:String(form.get('category')||'Pessoal'),priority:'Normal',reminderEnabled,reminderTime,done:false};setHomeTasks(items=>{const next=[entry,...items];localStorage.setItem('essence:tasks',JSON.stringify(next));return next});if(reminderEnabled)syncDatedReminder(entry.id,'Tarefa: '+title,entry.date,reminderTime)}else{const entry={id:id(),name:title,time:String(form.get('time')||''),category:String(form.get('category')||'Pessoal'),days:['SEG','TER','QUA','QUI','SEX','SÁB','DOM'],reminderEnabled,reminderTime,done:false};setHomeHabits(items=>{const next=[entry,...items];localStorage.setItem('essence:routine-items',JSON.stringify(next));return next});syncAppReminder(entry.id,'Hábito: '+title,reminderTime,reminderEnabled)}if(reminderEnabled)void requestReminderPermission();showNotice(quickCreate==='task'?'Tarefa adicionada ao dia':'Hábito adicionado ao dia');setQuickCreate(null)}}><label className="wide">{quickCreate==='task'?'O que você precisa fazer?':'Qual hábito deseja criar?'}<input name="title" placeholder={quickCreate==='task'?'Ex.: Enviar mensagem':'Ex.: Caminhar 20 minutos'} required autoFocus onFocus={event=>window.setTimeout(()=>event.currentTarget.scrollIntoView({behavior:'smooth',block:'center'}),120)}/></label><label>Horário<input name="time" type="time"/></label><label>Categoria<select name="category"><option>Pessoal</option><option>Saúde</option><option>Bem-estar</option><option>Trabalho</option><option>Casa</option><option>Estudos</option></select></label><label className="house-check"><input name="reminderEnabled" type="checkbox"/> Ativar lembrete</label><label>Horário do lembrete<input name="reminderTime" type="time" defaultValue="09:00"/></label><button className="primary wide">Adicionar ao meu dia</button></form></article>}
<div className="home-main-grid"><article className="card home-timeline"><div className="card-head home-timeline-header"><div><h3>Seu dia</h3><p>Tarefas e hábitos organizados por horário.</p></div><span className="home-pending-badge">{pendingCount} pendente(s)</span></div>{timeline.length?<div className="home-timeline-list">{timeline.map(item=><div className={`${item.kind==='habit'?'home-timeline-item habit-item':'home-timeline-item task-item'}${item.done?' is-done':''}`} key={item.kind+item.id}><input type="checkbox" checked={item.done} onChange={()=>{if(item.kind==='habit')completeHomeHabit(item.id);else completeHomeTask(item.id);showNotice(item.done?'Ação reaberta':'Ação concluída')}} aria-label={`Concluir ${item.title}`}/><div className="home-item-copy"><span className="home-item-meta"><i>{item.kind==='habit'?'HÁBITO':'TAREFA'}</i><small>{item.kind==='habit'?'🔥 1 dia':'Hoje'}</small><small className="home-time">{item.time?`◷ ${item.time}`:'Sem horário'}</small></span><b className="home-item-title"><span className="home-row-icon">{categoryIcon(item.category,item.title)}</span>{item.title}</b><small>{item.category}</small></div></div>)}</div>:<div className="home-day-empty"><span>✓</span><div><h3>Tudo em dia por aqui</h3><p>Você não tem tarefas ou hábitos pendentes para hoje.</p></div></div>}</article>
<article className="home-water-habit" aria-label="Hábito de hidratação"><div className="water-habit-head"><button type="button" className={'water-habit-check'+(waterToday>0?' is-done':'')} onClick={()=>{const total=registerHomeWater();showNotice(`Água registrada · ${total} ml hoje`)}} aria-label="Registrar 250 ml de água">○</button><div><span className="home-item-meta"><i>HÁBITO</i><small>🔥 hoje</small></span><b>💧 Beber 2 L de água</b></div><div className="water-amount-controls"><button type="button" disabled={waterToday===0} onClick={()=>{const total=unregisterHomeWater();showNotice(`Registro removido · ${total} ml hoje`)}} aria-label="Remover 250 ml">−</button><button type="button" onClick={()=>{const total=registerHomeWater();showNotice(`Água registrada · ${total} ml hoje`)}} aria-label="Adicionar 250 ml">+</button></div></div><div className="water-progress-copy"><span>{(waterToday/1000).toLocaleString('pt-BR',{minimumFractionDigits:waterToday%1000===0?0:2,maximumFractionDigits:2})} L de 2 L</span><b>{Math.min(100,Math.round(waterToday/2000*100))}%</b></div><div className="water-progress-track"><span style={{width:Math.min(100,Math.round(waterToday/2000*100))+'%'}}/></div><div className="water-cups" aria-hidden="true">{Array.from({length:8},(_,index)=><span className={index<Math.ceil(waterToday/250)?'filled':''} key={index}>▾</span>)}</div></article><article className="card wellbeing-card"><div className="card-head"><div><h3>Seu bem-estar hoje</h3><p>Um olhar rápido para diferentes áreas.</p></div></div><div className="wellbeing-grid"><button onClick={()=>openPage('nutrition')}><span>💧</span><b>{waterToday} ml</b><small>Hidratação</small></button><button onClick={()=>openPage('sleep')}><span>🌙</span><b>{sleep?.quality?`${sleep.quality}/5`:'—'}</b><small>Sono</small></button><button onClick={()=>openPage('diary')}><span>📘</span><b>{diaryCount}</b><small>Diário</small></button><button onClick={()=>openPage('workouts')}><span>🏋️</span><b>{workoutCount}</b><small>Treinos</small></button></div></article></div>
{(completedTasks.length>0||completedHabits.length>0)&&<article className="card home-completed"><div className="card-head"><div><h3>Concluídos hoje</h3><p>Pequenas ações também contam.</p></div><b>{completedTasks.length+completedHabits.length}</b></div><div>{completedTasks.slice(0,3).map(item=><span key={item.id}>✓ {item.title}</span>)}{completedHabits.slice(0,3).map(item=><span key={item.id}>✓ {item.name}</span>)}</div></article>}
<article className="home-message"><span>✨</span><div><b>Mensagem do dia</b><p>{dayProgress===100?'Você concluiu o que planejou. Agora também vale desacelerar.':dayProgress>=50?'Seu ritmo está acontecendo. Continue sem transformar cuidado em cobrança.':'Um passo possível vale mais do que um plano perfeito.'}</p></div></article>
</section>}
export default Home;
