import { useState } from 'react';
import type { Dispatch, SetStateAction } from 'react';
import { createId as id, today } from '../../shared/app-utils';

type Task={id:string;title:string;date:string;time?:string;category?:string;priority:string;reminderEnabled?:boolean;reminderTime?:string;done:boolean};
type Props={kind:'task'|'habit';onClose:()=>void;setTasks:Dispatch<SetStateAction<Task[]>>;setHabits:Dispatch<SetStateAction<any[]>>;onNotice:(message:string)=>void};

export default function TaskCreateModal({kind,onClose,setTasks,setHabits,onNotice}:Props){
  const [title,setTitle]=useState(''); const [date,setDate]=useState(today()); const [time,setTime]=useState(''); const [reminder,setReminder]=useState(false); const [reminderTime,setReminderTime]=useState('09:00'); const [priority,setPriority]=useState('Alta'); const [category,setCategory]=useState('Estudos'); const [repeat,setRepeat]=useState('Não repetir'); const [dayPriority,setDayPriority]=useState(false);
  const save=(event:React.FormEvent)=>{event.preventDefault();if(!title.trim())return;if(kind==='task'){const entry={id:id(),title:title.trim(),date,time,category,priority,reminderEnabled:reminder,reminderTime,done:false};setTasks(items=>{const next=[entry,...items];localStorage.setItem('essence:tasks',JSON.stringify(next));return next});}else{const entry={id:id(),name:title.trim(),time,category,days:['SEG','TER','QUA','QUI','SEX','SÁB','DOM'],reminderEnabled:reminder,reminderTime,done:false};setHabits(items=>{const next=[entry,...items];localStorage.setItem('essence:routine-items',JSON.stringify(next));return next});}onNotice(kind==='task'?'Tarefa adicionada ao dia':'Hábito adicionado ao dia');onClose()};
  return <div className="task-editor-overlay" role="dialog" aria-modal="true" aria-label="Nova tarefa"><form className="task-editor-modal" onSubmit={save}><header><div><h2>{kind==='task'?'Editar Tarefa':'Novo hábito'}</h2></div><button type="button" className="task-editor-close" onClick={onClose} aria-label="Fechar">×</button></header><div className="task-editor-fields"><label className="task-editor-wide">O que você precisa fazer?<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Fazer atividades da escola" required/></label><label className="task-editor-wide"><span>▣ &nbsp;Quando?</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="task-editor-wide"><span>◷ &nbsp;Horário? <small>(opcional)</small></span><input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><div className="task-editor-reminder"><span>♧ Lembrete {reminder&&time?`ativo para ${time}`:'desativado'}</span><button type="button" onClick={()=>setReminder(value=>!value)}>{reminder?'Desativar':'Ativar lembrete'}</button></div>{reminder&&<label className="task-editor-wide">Horário do lembrete<input type="time" value={reminderTime} onChange={e=>setReminderTime(e.target.value)}/></label>}<fieldset className="task-editor-wide"><legend>⚑ &nbsp;Prioridade</legend><div className="task-editor-priorities">{[['Alta','🔴'],['Média','🟡'],['Baixa','🟢']].map(([value,icon])=><button type="button" key={value} className={priority===value?'selected':''} onClick={()=>setPriority(value)}>{icon} {value}</button>)}</div></fieldset><label className="task-editor-wide"><span>◇ &nbsp;Categoria <button type="button" className="task-editor-link">+ Categoria personalizada</button></span><select value={category} onChange={e=>setCategory(e.target.value)}><option>📚 Estudos</option><option>Saúde</option><option>Pessoal</option><option>Trabalho</option><option>Casa</option></select></label><label className="task-editor-wide"><span>⟳ &nbsp;Repetir?</span><select value={repeat} onChange={e=>setRepeat(e.target.value)}><option>Não repetir</option><option>Diariamente</option><option>Semanalmente</option><option>Mensalmente</option></select></label><label className="task-editor-day-priority"><span>☆ <b>Marcar como Prioridade do Dia</b><small>Aparece com destaque em “Prioridades do Dia”</small></span><input type="checkbox" checked={dayPriority} onChange={e=>setDayPriority(e.target.checked)}/></label></div><footer><button type="button" className="task-editor-cancel" onClick={onClose}>Cancelar</button><button type="submit" className="task-editor-save">✓ &nbsp;Salvar tarefa</button></footer></form></div>;
}
